/* Generated by Yosys 0.50+0 (git sha1 6f9c515a2, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "./../../source/output_terminal.v:1.1-68.10" *)
module output_terminal(clk, selXY, selSign, Xin, Yin, Dout, Rdy, Vld, ISin);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:110.22-110.23" *)
  (* unused_bits = "11" *)
  wire [11:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [11:0] _043_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _044_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:110.22-110.23" *)
  (* unused_bits = "11" *)
  wire [11:0] _045_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [11:0] _047_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire [1:0] _052_;
  wire [1:0] _053_;
  wire _054_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _055_;
  (* src = "./../../source/output_terminal.v:8.18-8.22" *)
  output [11:0] Dout;
  wire [11:0] Dout;
  (* src = "./../../source/output_terminal.v:11.10-11.14" *)
  input ISin;
  wire ISin;
  (* src = "./../../source/output_terminal.v:25.6-25.11" *)
  wire ISreg;
  (* src = "./../../source/output_terminal.v:16.21-16.28" *)
  wire [6:0] LoadCtl;
  (* src = "./../../source/output_terminal.v:9.10-9.13" *)
  input Rdy;
  wire Rdy;
  (* src = "./../../source/output_terminal.v:10.11-10.14" *)
  output Vld;
  wire Vld;
  (* src = "./../../source/output_terminal.v:51.14-51.19" *)
  wire [11:0] Xcalc;
  (* src = "./../../source/output_terminal.v:6.16-6.19" *)
  input [1:0] Xin;
  wire [1:0] Xin;
  (* src = "./../../source/output_terminal.v:29.42-29.46" *)
  wire [1:0] Xin0;
  (* src = "./../../source/output_terminal.v:29.36-29.40" *)
  wire [1:0] Xin1;
  (* src = "./../../source/output_terminal.v:49.14-49.20" *)
  wire [11:0] Xin12b;
  (* src = "./../../source/output_terminal.v:29.30-29.34" *)
  wire [1:0] Xin2;
  (* src = "./../../source/output_terminal.v:29.24-29.28" *)
  wire [1:0] Xin3;
  (* src = "./../../source/output_terminal.v:29.18-29.22" *)
  wire [1:0] Xin4;
  (* src = "./../../source/output_terminal.v:29.12-29.16" *)
  wire [1:0] Xin5;
  (* src = "./../../source/output_terminal.v:51.21-51.26" *)
  wire [11:0] Ycalc;
  (* src = "./../../source/output_terminal.v:7.16-7.19" *)
  input [1:0] Yin;
  wire [1:0] Yin;
  (* src = "./../../source/output_terminal.v:30.42-30.46" *)
  wire [1:0] Yin0;
  (* src = "./../../source/output_terminal.v:30.36-30.40" *)
  wire [1:0] Yin1;
  (* src = "./../../source/output_terminal.v:50.14-50.20" *)
  wire [11:0] Yin12b;
  (* src = "./../../source/output_terminal.v:30.30-30.34" *)
  wire [1:0] Yin2;
  (* src = "./../../source/output_terminal.v:30.24-30.28" *)
  wire [1:0] Yin3;
  (* src = "./../../source/output_terminal.v:30.18-30.22" *)
  wire [1:0] Yin4;
  (* src = "./../../source/output_terminal.v:30.12-30.16" *)
  wire [1:0] Yin5;
  (* src = "./../../source/output_terminal.v:42.13-42.17" *)
  wire [11:0] bias;
  (* src = "./../../source/output_terminal.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "./../../source/output_terminal.v:5.10-5.17" *)
  input selSign;
  wire selSign;
  (* src = "./../../source/output_terminal.v:4.10-4.15" *)
  input selXY;
  wire selXY;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000100000000)
  ) _056_ (
    .I0(LoadCtl[4]),
    .I1(LoadCtl[3]),
    .I2(LoadCtl[2]),
    .I3(LoadCtl[1]),
    .I4(LoadCtl[0]),
    .I5(LoadCtl[5]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd65536)
  ) _057_ (
    .I0(LoadCtl[3]),
    .I1(LoadCtl[2]),
    .I2(LoadCtl[1]),
    .I3(LoadCtl[0]),
    .I4(LoadCtl[4]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _058_ (
    .I0(LoadCtl[2]),
    .I1(LoadCtl[1]),
    .I2(LoadCtl[0]),
    .I3(LoadCtl[3]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _059_ (
    .I0(LoadCtl[1]),
    .I1(LoadCtl[0]),
    .I2(LoadCtl[2]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _060_ (
    .I0(LoadCtl[0]),
    .I1(LoadCtl[1]),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _061_ (
    .I0(Xcalc[0]),
    .I1(Ycalc[0]),
    .I2(_055_[2]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _062_ (
    .I0(Ycalc[1]),
    .I1(Xcalc[1]),
    .I2(_055_[2]),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _063_ (
    .I0(Ycalc[2]),
    .I1(Xcalc[2]),
    .I2(_055_[2]),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _064_ (
    .I0(Ycalc[3]),
    .I1(Xcalc[3]),
    .I2(_055_[2]),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _065_ (
    .I0(Ycalc[4]),
    .I1(Xcalc[4]),
    .I2(_055_[2]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _066_ (
    .I0(Ycalc[5]),
    .I1(Xcalc[5]),
    .I2(_055_[2]),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _067_ (
    .I0(Ycalc[6]),
    .I1(Xcalc[6]),
    .I2(_055_[2]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _068_ (
    .I0(Ycalc[7]),
    .I1(Xcalc[7]),
    .I2(_055_[2]),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _069_ (
    .I0(Ycalc[8]),
    .I1(Xcalc[8]),
    .I2(_055_[2]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _070_ (
    .I0(Ycalc[9]),
    .I1(Xcalc[9]),
    .I2(_055_[2]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _071_ (
    .I0(Ycalc[10]),
    .I1(Xcalc[10]),
    .I2(_055_[2]),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _072_ (
    .I0(Ycalc[11]),
    .I1(Xcalc[11]),
    .I2(_055_[2]),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _073_ (
    .I0(_048_[0]),
    .I1(Yin0[0]),
    .I2(ISreg),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _074_ (
    .I0(Yin0[1]),
    .I1(_048_[1]),
    .I2(ISreg),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _075_ (
    .I0(Yin1[0]),
    .I1(_048_[2]),
    .I2(ISreg),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _076_ (
    .I0(Yin1[1]),
    .I1(_048_[3]),
    .I2(ISreg),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _077_ (
    .I0(Yin2[0]),
    .I1(_048_[4]),
    .I2(ISreg),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _078_ (
    .I0(Yin2[1]),
    .I1(_048_[5]),
    .I2(ISreg),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _079_ (
    .I0(Yin3[0]),
    .I1(_048_[6]),
    .I2(ISreg),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _080_ (
    .I0(Yin3[1]),
    .I1(_048_[7]),
    .I2(ISreg),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _081_ (
    .I0(Yin4[0]),
    .I1(_048_[8]),
    .I2(ISreg),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _082_ (
    .I0(Yin4[1]),
    .I1(_048_[9]),
    .I2(ISreg),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _083_ (
    .I0(Yin5[0]),
    .I1(_048_[10]),
    .I2(ISreg),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'haa3c)
  ) _084_ (
    .I0(_048_[11]),
    .I1(Yin5[1]),
    .I2(bias[11]),
    .I3(ISreg),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _085_ (
    .I0(Xin0[0]),
    .I1(_044_[0]),
    .I2(ISreg),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _086_ (
    .I0(Xin0[1]),
    .I1(_044_[1]),
    .I2(ISreg),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _087_ (
    .I0(Xin1[0]),
    .I1(_044_[2]),
    .I2(ISreg),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _088_ (
    .I0(Xin1[1]),
    .I1(_044_[3]),
    .I2(ISreg),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _089_ (
    .I0(Xin2[0]),
    .I1(_044_[4]),
    .I2(ISreg),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _090_ (
    .I0(Xin2[1]),
    .I1(_044_[5]),
    .I2(ISreg),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _091_ (
    .I0(Xin3[0]),
    .I1(_044_[6]),
    .I2(ISreg),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _092_ (
    .I0(Xin3[1]),
    .I1(_044_[7]),
    .I2(ISreg),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _093_ (
    .I0(Xin4[0]),
    .I1(_044_[8]),
    .I2(ISreg),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _094_ (
    .I0(Xin4[1]),
    .I1(_044_[9]),
    .I2(ISreg),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _095_ (
    .I0(Xin5[0]),
    .I1(_044_[10]),
    .I2(ISreg),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'haa3c)
  ) _096_ (
    .I0(_044_[11]),
    .I1(Xin5[1]),
    .I2(bias[11]),
    .I3(ISreg),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _097_ (
    .I0(Yin5[1]),
    .I1(bias[11]),
    .O(_047_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _098_ (
    .I0(Xin5[1]),
    .I1(bias[11]),
    .O(_043_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _099_ (
    .I(Xin0[0]),
    .O(_041_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _100_ (
    .I(Xin0[1]),
    .O(_041_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _101_ (
    .I(Xin1[0]),
    .O(_041_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _102_ (
    .I(Xin1[1]),
    .O(_041_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _103_ (
    .I(Xin2[0]),
    .O(_041_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _104_ (
    .I(Xin2[1]),
    .O(_041_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _105_ (
    .I(Xin3[0]),
    .O(_041_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _106_ (
    .I(Xin3[1]),
    .O(_041_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _107_ (
    .I(Xin4[0]),
    .O(_041_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _108_ (
    .I(Xin4[1]),
    .O(_041_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _109_ (
    .I(Xin5[0]),
    .O(_041_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _110_ (
    .I(Yin0[0]),
    .O(_045_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _111_ (
    .I(Yin0[1]),
    .O(_045_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _112_ (
    .I(Yin1[0]),
    .O(_045_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _113_ (
    .I(Yin1[1]),
    .O(_045_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _114_ (
    .I(Yin2[0]),
    .O(_045_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _115_ (
    .I(Yin2[1]),
    .O(_045_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _116_ (
    .I(Yin3[0]),
    .O(_045_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _117_ (
    .I(Yin3[1]),
    .O(_045_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _118_ (
    .I(Yin4[0]),
    .O(_045_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _119_ (
    .I(Yin4[1]),
    .O(_045_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _120_ (
    .I(Yin5[0]),
    .O(_045_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _121_ (
    .CI(1'h0),
    .CO(_042_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_044_[3:0]),
    .S(_041_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _122_ (
    .CI(_042_[3]),
    .CO(_042_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_044_[7:4]),
    .S(_041_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:55.14-55.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _123_ (
    .CI(_042_[7]),
    .CO(_042_[11:8]),
    .CYINIT(1'h0),
    .DI({ bias[11], 3'h0 }),
    .O(_044_[11:8]),
    .S({ _043_[11], _041_[10:8] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _124_ (
    .CI(1'h0),
    .CO(_046_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_048_[3:0]),
    .S(_045_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _125_ (
    .CI(_046_[3]),
    .CO(_046_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_048_[7:4]),
    .S(_045_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:56.14-56.32|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _126_ (
    .CI(_046_[7]),
    .CO(_046_[11:8]),
    .CYINIT(1'h0),
    .DI({ bias[11], 3'h0 }),
    .O(_048_[11:8]),
    .S({ _047_[11], _045_[10:8] })
  );
  BUFG _127_ (
    .I(_049_),
    .O(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:26.2-26.53|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _128_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_050_),
    .Q(ISreg),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _129_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_029_),
    .Q(Xcalc[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _130_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_032_),
    .Q(Xcalc[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _131_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_033_),
    .Q(Xcalc[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _132_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_034_),
    .Q(Xcalc[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _133_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_035_),
    .Q(Xcalc[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _134_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_036_),
    .Q(Xcalc[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _135_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_037_),
    .Q(Xcalc[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _136_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_038_),
    .Q(Xcalc[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _137_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_039_),
    .Q(Xcalc[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _138_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_040_),
    .Q(Xcalc[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _139_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_030_),
    .Q(Xcalc[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _140_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_031_),
    .Q(Xcalc[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _141_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_017_),
    .Q(Ycalc[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _142_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_020_),
    .Q(Ycalc[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _143_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_021_),
    .Q(Ycalc[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _144_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_022_),
    .Q(Ycalc[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _145_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_023_),
    .Q(Ycalc[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _146_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_024_),
    .Q(Ycalc[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _147_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_025_),
    .Q(Ycalc[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _148_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_026_),
    .Q(Ycalc[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _149_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_027_),
    .Q(Ycalc[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _150_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_028_),
    .Q(Ycalc[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _151_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_018_),
    .Q(Ycalc[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:52.2-63.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _152_ (
    .C(_054_),
    .CE(LoadCtl[6]),
    .D(_019_),
    .Q(Ycalc[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _153_ (
    .C(_054_),
    .CE(_004_),
    .D(_052_[0]),
    .Q(Xin5[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _154_ (
    .C(_054_),
    .CE(_004_),
    .D(_052_[1]),
    .Q(Xin5[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _155_ (
    .C(_054_),
    .CE(_003_),
    .D(_052_[0]),
    .Q(Xin4[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _156_ (
    .C(_054_),
    .CE(_003_),
    .D(_052_[1]),
    .Q(Xin4[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _157_ (
    .C(_054_),
    .CE(_002_),
    .D(_052_[0]),
    .Q(Xin3[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _158_ (
    .C(_054_),
    .CE(_002_),
    .D(_052_[1]),
    .Q(Xin3[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _159_ (
    .C(_054_),
    .CE(_001_),
    .D(_052_[0]),
    .Q(Xin2[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _160_ (
    .C(_054_),
    .CE(_001_),
    .D(_052_[1]),
    .Q(Xin2[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _161_ (
    .C(_054_),
    .CE(_000_),
    .D(_052_[0]),
    .Q(Xin1[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _162_ (
    .C(_054_),
    .CE(_000_),
    .D(_052_[1]),
    .Q(Xin1[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _163_ (
    .C(_054_),
    .CE(LoadCtl[0]),
    .D(_052_[0]),
    .Q(Xin0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _164_ (
    .C(_054_),
    .CE(LoadCtl[0]),
    .D(_052_[1]),
    .Q(Xin0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _165_ (
    .C(_054_),
    .CE(_004_),
    .D(_053_[0]),
    .Q(Yin5[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _166_ (
    .C(_054_),
    .CE(_004_),
    .D(_053_[1]),
    .Q(Yin5[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _167_ (
    .C(_054_),
    .CE(_003_),
    .D(_053_[0]),
    .Q(Yin4[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _168_ (
    .C(_054_),
    .CE(_003_),
    .D(_053_[1]),
    .Q(Yin4[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _169_ (
    .C(_054_),
    .CE(_002_),
    .D(_053_[0]),
    .Q(Yin3[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _170_ (
    .C(_054_),
    .CE(_002_),
    .D(_053_[1]),
    .Q(Yin3[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _171_ (
    .C(_054_),
    .CE(_001_),
    .D(_053_[0]),
    .Q(Yin2[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _172_ (
    .C(_054_),
    .CE(_001_),
    .D(_053_[1]),
    .Q(Yin2[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _173_ (
    .C(_054_),
    .CE(_000_),
    .D(_053_[0]),
    .Q(Yin1[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _174_ (
    .C(_054_),
    .CE(_000_),
    .D(_053_[1]),
    .Q(Yin1[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _175_ (
    .C(_054_),
    .CE(LoadCtl[0]),
    .D(_053_[0]),
    .Q(Yin0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:32.2-39.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _176_ (
    .C(_054_),
    .CE(LoadCtl[0]),
    .D(_053_[1]),
    .Q(Yin0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _177_ (
    .C(_054_),
    .CE(1'h1),
    .D(_051_),
    .Q(LoadCtl[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _178_ (
    .C(_054_),
    .CE(1'h1),
    .D(LoadCtl[0]),
    .Q(LoadCtl[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _179_ (
    .C(_054_),
    .CE(1'h1),
    .D(LoadCtl[1]),
    .Q(LoadCtl[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _180_ (
    .C(_054_),
    .CE(1'h1),
    .D(LoadCtl[2]),
    .Q(LoadCtl[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _181_ (
    .C(_054_),
    .CE(1'h1),
    .D(LoadCtl[3]),
    .Q(LoadCtl[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _182_ (
    .C(_054_),
    .CE(1'h1),
    .D(LoadCtl[4]),
    .Q(LoadCtl[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/output_terminal.v:17.5-22.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _183_ (
    .C(_054_),
    .CE(1'h1),
    .D(LoadCtl[5]),
    .Q(LoadCtl[6]),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  OBUF _184_ (
    .I(_005_),
    .O(Dout[0])
  );
  (* keep = 32'd1 *)
  OBUF _185_ (
    .I(_008_),
    .O(Dout[1])
  );
  (* keep = 32'd1 *)
  OBUF _186_ (
    .I(_006_),
    .O(Dout[10])
  );
  (* keep = 32'd1 *)
  OBUF _187_ (
    .I(_007_),
    .O(Dout[11])
  );
  (* keep = 32'd1 *)
  OBUF _188_ (
    .I(_009_),
    .O(Dout[2])
  );
  (* keep = 32'd1 *)
  OBUF _189_ (
    .I(_010_),
    .O(Dout[3])
  );
  (* keep = 32'd1 *)
  OBUF _190_ (
    .I(_011_),
    .O(Dout[4])
  );
  (* keep = 32'd1 *)
  OBUF _191_ (
    .I(_012_),
    .O(Dout[5])
  );
  (* keep = 32'd1 *)
  OBUF _192_ (
    .I(_013_),
    .O(Dout[6])
  );
  (* keep = 32'd1 *)
  OBUF _193_ (
    .I(_014_),
    .O(Dout[7])
  );
  (* keep = 32'd1 *)
  OBUF _194_ (
    .I(_015_),
    .O(Dout[8])
  );
  (* keep = 32'd1 *)
  OBUF _195_ (
    .I(_016_),
    .O(Dout[9])
  );
  (* keep = 32'd1 *)
  IBUF _196_ (
    .I(ISin),
    .O(_050_)
  );
  (* keep = 32'd1 *)
  IBUF _197_ (
    .I(Rdy),
    .O(_051_)
  );
  (* keep = 32'd1 *)
  OBUF _198_ (
    .I(LoadCtl[6]),
    .O(Vld)
  );
  (* keep = 32'd1 *)
  IBUF _199_ (
    .I(Xin[0]),
    .O(_052_[0])
  );
  (* keep = 32'd1 *)
  IBUF _200_ (
    .I(Xin[1]),
    .O(_052_[1])
  );
  (* keep = 32'd1 *)
  IBUF _201_ (
    .I(Yin[0]),
    .O(_053_[0])
  );
  (* keep = 32'd1 *)
  IBUF _202_ (
    .I(Yin[1]),
    .O(_053_[1])
  );
  (* keep = 32'd1 *)
  IBUF _203_ (
    .I(clk),
    .O(_049_)
  );
  (* keep = 32'd1 *)
  IBUF _204_ (
    .I(selSign),
    .O(bias[11])
  );
  (* keep = 32'd1 *)
  IBUF _205_ (
    .I(selXY),
    .O(_055_[2])
  );
  assign _055_[1:0] = { Xcalc[10], Ycalc[10] };
  assign _043_[10:0] = _041_[10:0];
  assign _047_[10:0] = _045_[10:0];
  assign Xin12b = { Xin5, Xin4, Xin3, Xin2, Xin1, Xin0 };
  assign Yin12b = { Yin5, Yin4, Yin3, Yin2, Yin1, Yin0 };
  assign bias[10:0] = 11'h000;
endmodule
