/* Generated by Yosys 0.50+0 (git sha1 6f9c515a2, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "./../../../../source/DDFS.v:1.1-65.10" *)
module DDFS(clk, En, FCW, selXY, selSign, Vld, Dout);
  wire [11:0] _00_;
  wire _01_;
  wire [19:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "./../../../../source/DDFS.v:8.16-8.20" *)
  output [11:0] Dout;
  wire [11:0] Dout;
  (* src = "./../../../../source/DDFS.v:3.8-3.10" *)
  input En;
  wire En;
  (* src = "./../../../../source/DDFS.v:4.15-4.18" *)
  input [19:0] FCW;
  wire [19:0] FCW;
  (* src = "./../../../../source/DDFS.v:7.9-7.12" *)
  output Vld;
  wire Vld;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[0] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[1] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[2] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[3] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[4] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[5] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[6] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  wire [1:0] \a[7] ;
  (* src = "./../../../../source/DDFS.v:12.13-12.14" *)
  (* unused_bits = "0 1" *)
  wire [1:0] \a[8] ;
  (* src = "./../../../../source/DDFS.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "./../../../../source/DDFS.v:13.13-13.15" *)
  wire [8:0] is;
  (* src = "./../../../../source/DDFS.v:13.17-13.20" *)
  wire [8:0] rdy;
  (* src = "./../../../../source/DDFS.v:6.8-6.15" *)
  input selSign;
  wire selSign;
  (* src = "./../../../../source/DDFS.v:5.8-5.13" *)
  input selXY;
  wire selXY;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[0] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[1] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[2] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[3] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[4] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[5] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[6] ;
  (* src = "./../../../../source/DDFS.v:14.13-14.16" *)
  wire [2:0] \stg[7] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[0] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[1] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[2] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[3] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[4] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[5] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[6] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[7] ;
  (* src = "./../../../../source/DDFS.v:10.13-10.14" *)
  wire [1:0] \x[8] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[0] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[1] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[2] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[3] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[4] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[5] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[6] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[7] ;
  (* src = "./../../../../source/DDFS.v:11.13-11.14" *)
  wire [1:0] \y[8] ;
  (* keep = 32'd1 *)
  OBUF _07_ (
    .I(_00_[0]),
    .O(Dout[0])
  );
  (* keep = 32'd1 *)
  OBUF _08_ (
    .I(_00_[1]),
    .O(Dout[1])
  );
  (* keep = 32'd1 *)
  OBUF _09_ (
    .I(_00_[10]),
    .O(Dout[10])
  );
  (* keep = 32'd1 *)
  OBUF _10_ (
    .I(_00_[11]),
    .O(Dout[11])
  );
  (* keep = 32'd1 *)
  OBUF _11_ (
    .I(_00_[2]),
    .O(Dout[2])
  );
  (* keep = 32'd1 *)
  OBUF _12_ (
    .I(_00_[3]),
    .O(Dout[3])
  );
  (* keep = 32'd1 *)
  OBUF _13_ (
    .I(_00_[4]),
    .O(Dout[4])
  );
  (* keep = 32'd1 *)
  OBUF _14_ (
    .I(_00_[5]),
    .O(Dout[5])
  );
  (* keep = 32'd1 *)
  OBUF _15_ (
    .I(_00_[6]),
    .O(Dout[6])
  );
  (* keep = 32'd1 *)
  OBUF _16_ (
    .I(_00_[7]),
    .O(Dout[7])
  );
  (* keep = 32'd1 *)
  OBUF _17_ (
    .I(_00_[8]),
    .O(Dout[8])
  );
  (* keep = 32'd1 *)
  OBUF _18_ (
    .I(_00_[9]),
    .O(Dout[9])
  );
  (* keep = 32'd1 *)
  IBUF _19_ (
    .I(En),
    .O(_01_)
  );
  (* keep = 32'd1 *)
  IBUF _20_ (
    .I(FCW[0]),
    .O(_02_[0])
  );
  (* keep = 32'd1 *)
  IBUF _21_ (
    .I(FCW[1]),
    .O(_02_[1])
  );
  (* keep = 32'd1 *)
  IBUF _22_ (
    .I(FCW[10]),
    .O(_02_[10])
  );
  (* keep = 32'd1 *)
  IBUF _23_ (
    .I(FCW[11]),
    .O(_02_[11])
  );
  (* keep = 32'd1 *)
  IBUF _24_ (
    .I(FCW[12]),
    .O(_02_[12])
  );
  (* keep = 32'd1 *)
  IBUF _25_ (
    .I(FCW[13]),
    .O(_02_[13])
  );
  (* keep = 32'd1 *)
  IBUF _26_ (
    .I(FCW[14]),
    .O(_02_[14])
  );
  (* keep = 32'd1 *)
  IBUF _27_ (
    .I(FCW[15]),
    .O(_02_[15])
  );
  (* keep = 32'd1 *)
  IBUF _28_ (
    .I(FCW[16]),
    .O(_02_[16])
  );
  (* keep = 32'd1 *)
  IBUF _29_ (
    .I(FCW[17]),
    .O(_02_[17])
  );
  (* keep = 32'd1 *)
  IBUF _30_ (
    .I(FCW[18]),
    .O(_02_[18])
  );
  (* keep = 32'd1 *)
  IBUF _31_ (
    .I(FCW[19]),
    .O(_02_[19])
  );
  (* keep = 32'd1 *)
  IBUF _32_ (
    .I(FCW[2]),
    .O(_02_[2])
  );
  (* keep = 32'd1 *)
  IBUF _33_ (
    .I(FCW[3]),
    .O(_02_[3])
  );
  (* keep = 32'd1 *)
  IBUF _34_ (
    .I(FCW[4]),
    .O(_02_[4])
  );
  (* keep = 32'd1 *)
  IBUF _35_ (
    .I(FCW[5]),
    .O(_02_[5])
  );
  (* keep = 32'd1 *)
  IBUF _36_ (
    .I(FCW[6]),
    .O(_02_[6])
  );
  (* keep = 32'd1 *)
  IBUF _37_ (
    .I(FCW[7]),
    .O(_02_[7])
  );
  (* keep = 32'd1 *)
  IBUF _38_ (
    .I(FCW[8]),
    .O(_02_[8])
  );
  (* keep = 32'd1 *)
  IBUF _39_ (
    .I(FCW[9]),
    .O(_02_[9])
  );
  (* keep = 32'd1 *)
  OBUF _40_ (
    .I(_03_),
    .O(Vld)
  );
  (* keep = 32'd1 *)
  IBUF _41_ (
    .I(clk),
    .O(_04_)
  );
  (* keep = 32'd1 *)
  IBUF _42_ (
    .I(selSign),
    .O(_05_)
  );
  (* keep = 32'd1 *)
  IBUF _43_ (
    .I(selXY),
    .O(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[0].u_ce  (
    .Ain(\a[0] ),
    .Aout(\a[1] ),
    .ISin(is[0]),
    .ISout(is[1]),
    .Rdy(rdy[0]),
    .Stg(3'h0),
    .Vld(rdy[1]),
    .Xin(2'hx),
    .Xout(\x[1] ),
    .Yin(2'hx),
    .Yout(\y[1] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[1].u_ce  (
    .Ain(\a[1] ),
    .Aout(\a[2] ),
    .ISin(is[1]),
    .ISout(is[2]),
    .Rdy(rdy[1]),
    .Stg(3'h1),
    .Vld(rdy[2]),
    .Xin(\x[1] ),
    .Xout(\x[2] ),
    .Yin(\y[1] ),
    .Yout(\y[2] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[2].u_ce  (
    .Ain(\a[2] ),
    .Aout(\a[3] ),
    .ISin(is[2]),
    .ISout(is[3]),
    .Rdy(rdy[2]),
    .Stg(3'h2),
    .Vld(rdy[3]),
    .Xin(\x[2] ),
    .Xout(\x[3] ),
    .Yin(\y[2] ),
    .Yout(\y[3] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[3].u_ce  (
    .Ain(\a[3] ),
    .Aout(\a[4] ),
    .ISin(is[3]),
    .ISout(is[4]),
    .Rdy(rdy[3]),
    .Stg(3'h3),
    .Vld(rdy[4]),
    .Xin(\x[3] ),
    .Xout(\x[4] ),
    .Yin(\y[3] ),
    .Yout(\y[4] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[4].u_ce  (
    .Ain(\a[4] ),
    .Aout(\a[5] ),
    .ISin(is[4]),
    .ISout(is[5]),
    .Rdy(rdy[4]),
    .Stg(3'h4),
    .Vld(rdy[5]),
    .Xin(\x[4] ),
    .Xout(\x[5] ),
    .Yin(\y[4] ),
    .Yout(\y[5] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[5].u_ce  (
    .Ain(\a[5] ),
    .Aout(\a[6] ),
    .ISin(is[5]),
    .ISout(is[6]),
    .Rdy(rdy[5]),
    .Stg(3'h5),
    .Vld(rdy[6]),
    .Xin(\x[5] ),
    .Xout(\x[6] ),
    .Yin(\y[5] ),
    .Yout(\y[6] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[6].u_ce  (
    .Ain(\a[6] ),
    .Aout(\a[7] ),
    .ISin(is[6]),
    .ISout(is[7]),
    .Rdy(rdy[6]),
    .Stg(3'h6),
    .Vld(rdy[7]),
    .Xin(\x[6] ),
    .Xout(\x[7] ),
    .Yin(\y[6] ),
    .Yout(\y[7] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:36.19-49.5" *)
  cordic_element \genblk1[7].u_ce  (
    .Ain(\a[7] ),
    .Aout(\a[8] ),
    .ISin(is[7]),
    .ISout(is[8]),
    .Rdy(rdy[7]),
    .Stg(3'h7),
    .Vld(rdy[8]),
    .Xin(\x[7] ),
    .Xout(\x[8] ),
    .Yin(\y[7] ),
    .Yout(\y[8] ),
    .clk(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:53.18-63.3" *)
  output_terminal u_ot (
    .Dout(_00_),
    .ISin(is[8]),
    .Rdy(rdy[8]),
    .Vld(_03_),
    .Xin(\x[8] ),
    .Yin(\y[8] ),
    .clk(_04_),
    .selSign(_05_),
    .selXY(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../../../source/DDFS.v:24.20-31.3" *)
  phase_accumulator u_pa (
    .Aout(\a[0] ),
    .En(_01_),
    .FCW(_02_),
    .ISout(is[0]),
    .Vld(rdy[0]),
    .clk(_04_)
  );
  assign \stg[0]  = 3'h0;
  assign \stg[1]  = 3'h1;
  assign \stg[2]  = 3'h2;
  assign \stg[3]  = 3'h3;
  assign \stg[4]  = 3'h4;
  assign \stg[5]  = 3'h5;
  assign \stg[6]  = 3'h6;
  assign \stg[7]  = 3'h7;
  assign \x[0]  = 2'hx;
  assign \y[0]  = 2'hx;
endmodule
