/* Generated by Yosys 0.50+0 (git sha1 6f9c515a2, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */
(* blackbox *)
(* top =  1  *)
(* src = "./../../source/cordic_element.v:1.1-121.10" *)
module cordic_element(clk, Xin, Xout, Yin, Yout, Ain, Aout, ISin, ISout, Stg, Rdy, Vld);
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _000_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _001_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _002_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _003_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _004_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _005_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _006_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [7:0] _007_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.12-84.14" *)
  wire _008_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:84.16-84.18" *)
  wire _009_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _010_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _011_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _012_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _013_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _014_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _015_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _016_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _017_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _018_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _019_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _020_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _021_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:108.22-108.23" *)
  wire [11:0] _052_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _053_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [11:0] _054_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _055_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:108.22-108.23" *)
  wire [11:0] _056_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [11:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:86.15-86.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:86.15-86.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [11:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/cordic_element.v:86.15-86.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _062_;
  wire _063_;
  wire [1:0] _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire [1:0] _068_;
  wire [1:0] _069_;
  wire _070_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:128.21-128.23" *)
  wire [11:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _072_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:128.21-128.23" *)
  wire [11:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:128.21-128.23" *)
  wire [11:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 11" *)
  wire [11:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [11:0] _079_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _083_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _084_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _085_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _086_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _088_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _089_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _090_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _091_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _092_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _093_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _094_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [4:0] _095_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _096_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _097_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _098_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _099_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _100_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _101_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _102_;
  (* src = "./../../source/cordic_element.v:106.20-106.22" *)
  wire [1:0] A_;
  (* src = "./../../source/cordic_element.v:75.34-75.39" *)
  wire [11:0] Acalc;
  (* src = "./../../source/cordic_element.v:8.15-8.18" *)
  input [1:0] Ain;
  wire [1:0] Ain;
  (* src = "./../../source/cordic_element.v:43.42-43.46" *)
  wire [1:0] Ain0;
  (* src = "./../../source/cordic_element.v:43.36-43.40" *)
  wire [1:0] Ain1;
  (* src = "./../../source/cordic_element.v:73.21-73.27" *)
  wire [11:0] Ain12b;
  (* src = "./../../source/cordic_element.v:43.30-43.34" *)
  wire [1:0] Ain2;
  (* src = "./../../source/cordic_element.v:43.24-43.28" *)
  wire [1:0] Ain3;
  (* src = "./../../source/cordic_element.v:43.18-43.22" *)
  wire [1:0] Ain4;
  (* src = "./../../source/cordic_element.v:43.12-43.16" *)
  wire [1:0] Ain5;
  (* src = "./../../source/cordic_element.v:9.16-9.20" *)
  output [1:0] Aout;
  wire [1:0] Aout;
  (* src = "./../../source/cordic_element.v:10.11-10.15" *)
  input ISin;
  wire ISin;
  (* src = "./../../source/cordic_element.v:11.14-11.19" *)
  output ISout;
  wire ISout;
  (* src = "./../../source/cordic_element.v:28.21-28.28" *)
  wire [6:0] LoadCtl;
  (* src = "./../../source/cordic_element.v:13.11-13.14" *)
  input Rdy;
  wire Rdy;
  (* src = "./../../source/cordic_element.v:12.14-12.17" *)
  input [2:0] Stg;
  wire [2:0] Stg;
  (* src = "./../../source/cordic_element.v:14.12-14.15" *)
  output Vld;
  wire Vld;
  (* src = "./../../source/cordic_element.v:106.12-106.14" *)
  wire [1:0] X_;
  (* src = "./../../source/cordic_element.v:75.20-75.25" *)
  wire [11:0] Xcalc;
  (* src = "./../../source/cordic_element.v:4.16-4.19" *)
  input [1:0] Xin;
  wire [1:0] Xin;
  (* src = "./../../source/cordic_element.v:41.42-41.46" *)
  wire [1:0] Xin0;
  (* src = "./../../source/cordic_element.v:41.36-41.40" *)
  wire [1:0] Xin1;
  (* src = "./../../source/cordic_element.v:71.21-71.27" *)
  wire [11:0] Xin12b;
  (* src = "./../../source/cordic_element.v:41.30-41.34" *)
  wire [1:0] Xin2;
  (* src = "./../../source/cordic_element.v:41.24-41.28" *)
  wire [1:0] Xin3;
  (* src = "./../../source/cordic_element.v:41.18-41.22" *)
  wire [1:0] Xin4;
  (* src = "./../../source/cordic_element.v:41.12-41.16" *)
  wire [1:0] Xin5;
  (* src = "./../../source/cordic_element.v:5.17-5.21" *)
  output [1:0] Xout;
  wire [1:0] Xout;
  (* src = "./../../source/cordic_element.v:106.16-106.18" *)
  wire [1:0] Y_;
  (* src = "./../../source/cordic_element.v:75.27-75.32" *)
  wire [11:0] Ycalc;
  (* src = "./../../source/cordic_element.v:6.16-6.19" *)
  input [1:0] Yin;
  wire [1:0] Yin;
  (* src = "./../../source/cordic_element.v:42.42-42.46" *)
  wire [1:0] Yin0;
  (* src = "./../../source/cordic_element.v:42.36-42.40" *)
  wire [1:0] Yin1;
  (* src = "./../../source/cordic_element.v:72.21-72.27" *)
  wire [11:0] Yin12b;
  (* src = "./../../source/cordic_element.v:42.30-42.34" *)
  wire [1:0] Yin2;
  (* src = "./../../source/cordic_element.v:42.24-42.28" *)
  wire [1:0] Yin3;
  (* src = "./../../source/cordic_element.v:42.18-42.22" *)
  wire [1:0] Yin4;
  (* src = "./../../source/cordic_element.v:42.12-42.16" *)
  wire [1:0] Yin5;
  (* src = "./../../source/cordic_element.v:7.17-7.21" *)
  output [1:0] Yout;
  wire [1:0] Yout;
  (* src = "./../../source/cordic_element.v:55.20-55.24" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8" *)
  wire [11:0] atan;
  (* src = "./../../source/cordic_element.v:17.20-17.25" *)
  wire [11:0] atan0;
  (* src = "./../../source/cordic_element.v:18.20-18.25" *)
  wire [11:0] atan1;
  (* src = "./../../source/cordic_element.v:19.20-19.25" *)
  wire [11:0] atan2;
  (* src = "./../../source/cordic_element.v:20.20-20.25" *)
  wire [11:0] atan3;
  (* src = "./../../source/cordic_element.v:21.20-21.25" *)
  wire [11:0] atan4;
  (* src = "./../../source/cordic_element.v:22.20-22.25" *)
  wire [11:0] atan5;
  (* src = "./../../source/cordic_element.v:23.20-23.25" *)
  wire [11:0] atan6;
  (* src = "./../../source/cordic_element.v:24.20-24.25" *)
  wire [11:0] atan7;
  (* src = "./../../source/cordic_element.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "./../../source/cordic_element.v:16.20-16.28" *)
  wire [11:0] oneOverK;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _103_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _104_ (
    .I0(_000_[5]),
    .I1(_000_[4]),
    .O(_071_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _105_ (
    .I0(LoadCtl[0]),
    .I1(LoadCtl[1]),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _106_ (
    .I0(LoadCtl[0]),
    .I1(_084_[1]),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _107_ (
    .I0(LoadCtl[1]),
    .I1(LoadCtl[2]),
    .O(_084_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _108_ (
    .I0(_085_[0]),
    .I1(LoadCtl[3]),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h01)
  ) _109_ (
    .I0(LoadCtl[1]),
    .I1(LoadCtl[2]),
    .I2(LoadCtl[0]),
    .O(_085_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h40)
  ) _110_ (
    .I0(LoadCtl[3]),
    .I1(_085_[0]),
    .I2(LoadCtl[4]),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h1000)
  ) _111_ (
    .I0(LoadCtl[3]),
    .I1(LoadCtl[4]),
    .I2(_085_[0]),
    .I3(LoadCtl[5]),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _112_ (
    .I0(_073_[0]),
    .I1(_071_[0]),
    .I2(Ain5[1]),
    .O(_056_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hc2)
  ) _113_ (
    .I0(_000_[4]),
    .I1(_000_[6]),
    .I2(_000_[5]),
    .O(_071_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _114_ (
    .I0(_073_[1]),
    .I1(_071_[1]),
    .I2(Ain5[1]),
    .O(_056_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hbc)
  ) _115_ (
    .I0(_000_[6]),
    .I1(_000_[5]),
    .I2(_000_[4]),
    .O(_071_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _116_ (
    .I0(_073_[2]),
    .I1(_071_[2]),
    .I2(Ain5[1]),
    .O(_056_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _117_ (
    .I0(_000_[5]),
    .I1(_000_[6]),
    .I2(_000_[4]),
    .O(_071_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd301986032)
  ) _118_ (
    .I0(_000_[4]),
    .I1(_000_[6]),
    .I2(_073_[3]),
    .I3(_000_[5]),
    .I4(Ain5[1]),
    .O(_056_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _119_ (
    .I0(_073_[4]),
    .I1(_071_[4]),
    .I2(Ain5[1]),
    .O(_056_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hb4)
  ) _120_ (
    .I0(_000_[6]),
    .I1(_000_[5]),
    .I2(_000_[4]),
    .O(_071_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd7860464)
  ) _121_ (
    .I0(_000_[4]),
    .I1(_000_[5]),
    .I2(_073_[5]),
    .I3(_000_[6]),
    .I4(Ain5[1]),
    .O(_056_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd805546666)
  ) _122_ (
    .I0(_073_[6]),
    .I1(_000_[4]),
    .I2(_000_[6]),
    .I3(_000_[5]),
    .I4(Ain5[1]),
    .O(_056_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _123_ (
    .I0(_073_[7]),
    .I1(_071_[7]),
    .I2(Ain5[1]),
    .O(_056_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _124_ (
    .I0(_073_[8]),
    .I1(_071_[8]),
    .I2(Ain5[1]),
    .O(_056_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _125_ (
    .I0(_000_[6]),
    .I1(_000_[4]),
    .O(_071_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _126_ (
    .I0(Ain5[1]),
    .I1(_073_[9]),
    .O(_056_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _127_ (
    .I0(Ain5[1]),
    .I1(_073_[10]),
    .O(_056_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _128_ (
    .I0(Ain5[1]),
    .I1(_073_[11]),
    .O(_056_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd861270256)
  ) _129_ (
    .I0(_089_[0]),
    .I1(_089_[1]),
    .I2(_079_[0]),
    .I3(_000_[4]),
    .I4(Ain5[1]),
    .O(_052_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _130_ (
    .I0(Yin2[0]),
    .I1(Yin3[0]),
    .I2(Yin2[1]),
    .I3(Yin3[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_089_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _131_ (
    .I0(Yin0[0]),
    .I1(Yin1[0]),
    .I2(Yin0[1]),
    .I3(Yin1[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_089_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd861270256)
  ) _132_ (
    .I0(_095_[0]),
    .I1(_087_[1]),
    .I2(_079_[1]),
    .I3(_000_[4]),
    .I4(Ain5[1]),
    .O(_052_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _133_ (
    .I0(Yin2[1]),
    .I1(Yin3[1]),
    .I2(Yin3[0]),
    .I3(Yin4[0]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_087_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _134_ (
    .I0(Yin0[1]),
    .I1(Yin1[1]),
    .I2(Yin1[0]),
    .I3(Yin2[0]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_095_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1157624048)
  ) _135_ (
    .I0(_083_[1]),
    .I1(_000_[4]),
    .I2(_079_[2]),
    .I3(_088_[2]),
    .I4(Ain5[1]),
    .O(_052_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _136_ (
    .I0(Yin3[0]),
    .I1(Yin4[0]),
    .I2(Yin3[1]),
    .I3(Yin4[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_083_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _137_ (
    .I0(Yin1[0]),
    .I1(Yin1[1]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _138_ (
    .I0(Yin2[0]),
    .I1(Yin2[1]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _139_ (
    .I0(_001_),
    .I1(_002_),
    .O(_088_[2]),
    .S(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1157624048)
  ) _140_ (
    .I0(_080_[1]),
    .I1(_000_[4]),
    .I2(_079_[3]),
    .I3(_080_[2]),
    .I4(Ain5[1]),
    .O(_052_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _141_ (
    .I0(Yin3[1]),
    .I1(Yin4[1]),
    .I2(Yin4[0]),
    .I3(Yin5[0]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_080_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _142_ (
    .I0(Yin1[1]),
    .I1(Yin2[0]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _143_ (
    .I0(Yin2[1]),
    .I1(Yin3[0]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _144_ (
    .I0(_003_),
    .I1(_004_),
    .O(_080_[2]),
    .S(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1429467376)
  ) _145_ (
    .I0(_090_[0]),
    .I1(_089_[1]),
    .I2(_079_[4]),
    .I3(_000_[4]),
    .I4(Ain5[1]),
    .O(_052_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _146_ (
    .I0(Yin4[0]),
    .I1(Yin5[0]),
    .I2(Yin4[1]),
    .I3(Yin5[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_090_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1429467376)
  ) _147_ (
    .I0(_087_[0]),
    .I1(_087_[1]),
    .I2(_079_[5]),
    .I3(_000_[4]),
    .I4(Ain5[1]),
    .O(_052_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _148_ (
    .I0(Yin4[1]),
    .I1(Yin5[0]),
    .I2(Yin5[1]),
    .I3(_000_[5]),
    .I4(_000_[6]),
    .O(_087_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd1429467376)
  ) _149_ (
    .I0(_082_[1]),
    .I1(_083_[1]),
    .I2(_079_[6]),
    .I3(_000_[4]),
    .I4(Ain5[1]),
    .O(_052_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h3335)
  ) _150_ (
    .I0(Yin5[0]),
    .I1(Yin5[1]),
    .I2(_000_[5]),
    .I3(_000_[6]),
    .O(_082_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2855530736)
  ) _151_ (
    .I0(Yin5[1]),
    .I1(_080_[1]),
    .I2(_079_[7]),
    .I3(_000_[4]),
    .I4(Ain5[1]),
    .O(_052_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h3a)
  ) _152_ (
    .I0(_079_[8]),
    .I1(_077_[8]),
    .I2(Ain5[1]),
    .O(_052_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd255004501)
  ) _153_ (
    .I0(Yin4[0]),
    .I1(Yin4[1]),
    .I2(Yin5[1]),
    .I3(_000_[4]),
    .I4(_000_[5]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'h3335)
  ) _154_ (
    .I0(Yin5[0]),
    .I1(Yin5[1]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _155_ (
    .I0(_005_),
    .I1(_006_),
    .O(_077_[8]),
    .S(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _156_ (
    .I0(_007_[2]),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _157_ (
    .I0(_007_[2]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:85.46-85.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _158_ (
    .I0(_010_),
    .I1(_011_),
    .O(_008_),
    .S(_000_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _159_ (
    .I0(Yin4[1]),
    .I1(Yin5[0]),
    .I2(Yin5[1]),
    .I3(_000_[5]),
    .I4(_000_[6]),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _160_ (
    .I0(Yin5[1]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:86.46-86.71|/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _161_ (
    .I0(_012_),
    .I1(_013_),
    .O(_009_),
    .S(_000_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _162_ (
    .I0(_008_),
    .I1(_009_),
    .O(_052_[9]),
    .S(Ain5[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _163_ (
    .I0(_014_[1]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4294836226)
  ) _164_ (
    .I0(Yin5[0]),
    .I1(_000_[5]),
    .I2(_000_[6]),
    .I3(_000_[4]),
    .I4(Yin5[1]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _165_ (
    .I0(_015_),
    .I1(_016_),
    .O(_052_[10]),
    .S(Ain5[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _166_ (
    .I0(_079_[11]),
    .I1(Yin5[1]),
    .I2(Ain5[1]),
    .O(_052_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h4f)
  ) _167_ (
    .I0(_092_[0]),
    .I1(_085_[0]),
    .I2(_092_[2]),
    .O(A_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _168_ (
    .I0(Acalc[10]),
    .I1(Acalc[8]),
    .I2(Acalc[6]),
    .I3(LoadCtl[4]),
    .I4(LoadCtl[3]),
    .O(_092_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff00ff0f0f7777)
  ) _169_ (
    .I0(Acalc[4]),
    .I1(LoadCtl[2]),
    .I2(Acalc[2]),
    .I3(Acalc[0]),
    .I4(LoadCtl[1]),
    .I5(LoadCtl[0]),
    .O(_092_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h4f)
  ) _170_ (
    .I0(_091_[0]),
    .I1(_085_[0]),
    .I2(_091_[2]),
    .O(A_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _171_ (
    .I0(Acalc[11]),
    .I1(Acalc[9]),
    .I2(Acalc[7]),
    .I3(LoadCtl[4]),
    .I4(LoadCtl[3]),
    .O(_091_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff00ff0f0f7777)
  ) _172_ (
    .I0(Acalc[5]),
    .I1(LoadCtl[2]),
    .I2(Acalc[3]),
    .I3(Acalc[1]),
    .I4(LoadCtl[1]),
    .I5(LoadCtl[0]),
    .O(_091_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h4f)
  ) _173_ (
    .I0(_094_[0]),
    .I1(_085_[0]),
    .I2(_094_[2]),
    .O(Y_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _174_ (
    .I0(Ycalc[10]),
    .I1(Ycalc[8]),
    .I2(Ycalc[6]),
    .I3(LoadCtl[4]),
    .I4(LoadCtl[3]),
    .O(_094_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff00ff0f0f7777)
  ) _175_ (
    .I0(Ycalc[4]),
    .I1(LoadCtl[2]),
    .I2(Ycalc[2]),
    .I3(Ycalc[0]),
    .I4(LoadCtl[1]),
    .I5(LoadCtl[0]),
    .O(_094_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h4f)
  ) _176_ (
    .I0(_096_[0]),
    .I1(_085_[0]),
    .I2(_096_[2]),
    .O(Y_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _177_ (
    .I0(Ycalc[11]),
    .I1(Ycalc[9]),
    .I2(Ycalc[7]),
    .I3(LoadCtl[4]),
    .I4(LoadCtl[3]),
    .O(_096_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff00ff0f0f7777)
  ) _178_ (
    .I0(Ycalc[5]),
    .I1(LoadCtl[2]),
    .I2(Ycalc[3]),
    .I3(Ycalc[1]),
    .I4(LoadCtl[1]),
    .I5(LoadCtl[0]),
    .O(_096_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0f0f0f0ffffff88)
  ) _179_ (
    .I0(Xcalc[4]),
    .I1(_084_[1]),
    .I2(Xcalc[0]),
    .I3(_084_[3]),
    .I4(_084_[4]),
    .I5(LoadCtl[0]),
    .O(X_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd202)
  ) _180_ (
    .I0(Xcalc[10]),
    .I1(Xcalc[8]),
    .I2(LoadCtl[4]),
    .I3(LoadCtl[2]),
    .I4(LoadCtl[1]),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT3 #(
    .INIT(8'h02)
  ) _181_ (
    .I0(Xcalc[6]),
    .I1(LoadCtl[2]),
    .I2(LoadCtl[1]),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _182_ (
    .I0(_017_),
    .I1(_018_),
    .O(_084_[4]),
    .S(LoadCtl[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _183_ (
    .I0(LoadCtl[1]),
    .I1(Xcalc[2]),
    .O(_084_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h4f)
  ) _184_ (
    .I0(_086_[0]),
    .I1(_085_[0]),
    .I2(_086_[2]),
    .O(X_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _185_ (
    .I0(Xcalc[11]),
    .I1(Xcalc[9]),
    .I2(Xcalc[7]),
    .I3(LoadCtl[4]),
    .I4(LoadCtl[3]),
    .O(_086_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff00ff0f0f7777)
  ) _186_ (
    .I0(Xcalc[5]),
    .I1(LoadCtl[2]),
    .I2(Xcalc[3]),
    .I3(Xcalc[1]),
    .I4(LoadCtl[1]),
    .I5(LoadCtl[0]),
    .O(_086_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccca)
  ) _187_ (
    .I0(Ain5[1]),
    .I1(_062_[2]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccc5)
  ) _188_ (
    .I0(Ain5[1]),
    .I1(_062_[3]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccc5)
  ) _189_ (
    .I0(Ain5[1]),
    .I1(_062_[4]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccca)
  ) _190_ (
    .I0(Ain5[1]),
    .I1(_062_[5]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccc5)
  ) _191_ (
    .I0(Ain5[1]),
    .I1(_062_[6]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccc5)
  ) _192_ (
    .I0(Ain5[1]),
    .I1(_062_[7]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccca)
  ) _193_ (
    .I0(Ain5[1]),
    .I1(_062_[8]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccca)
  ) _194_ (
    .I0(Ain5[1]),
    .I1(_062_[9]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccc5)
  ) _195_ (
    .I0(Ain5[1]),
    .I1(_062_[10]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hccca)
  ) _196_ (
    .I0(Ain5[1]),
    .I1(_062_[11]),
    .I2(_071_[7]),
    .I3(_000_[6]),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _197_ (
    .I0(_071_[8]),
    .I1(_000_[5]),
    .O(_071_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hf8)
  ) _198_ (
    .I0(_000_[5]),
    .I1(_000_[4]),
    .I2(_000_[6]),
    .O(_071_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hbe)
  ) _199_ (
    .I0(_000_[4]),
    .I1(_000_[6]),
    .I2(_000_[5]),
    .O(_071_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _200_ (
    .I0(_089_[0]),
    .I1(_089_[1]),
    .I2(_000_[4]),
    .O(_077_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _201_ (
    .I0(_095_[0]),
    .I1(_087_[1]),
    .I2(_000_[4]),
    .O(_077_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hd0)
  ) _202_ (
    .I0(_000_[4]),
    .I1(_083_[1]),
    .I2(_088_[2]),
    .O(_077_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hd0)
  ) _203_ (
    .I0(_000_[4]),
    .I1(_080_[1]),
    .I2(_080_[2]),
    .O(_077_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _204_ (
    .I0(_090_[0]),
    .I1(_089_[1]),
    .I2(_000_[4]),
    .O(_077_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _205_ (
    .I0(_087_[0]),
    .I1(_087_[1]),
    .I2(_000_[4]),
    .O(_077_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _206_ (
    .I0(_082_[1]),
    .I1(_083_[1]),
    .I2(_000_[4]),
    .O(_077_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h5c)
  ) _207_ (
    .I0(Yin5[1]),
    .I1(_080_[1]),
    .I2(_000_[4]),
    .O(_077_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h5c)
  ) _208_ (
    .I0(Yin5[1]),
    .I1(_087_[0]),
    .I2(_000_[4]),
    .O(_077_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h5c)
  ) _209_ (
    .I0(Yin5[1]),
    .I1(_082_[1]),
    .I2(_000_[4]),
    .O(_077_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _210_ (
    .I0(_081_[0]),
    .I1(_081_[1]),
    .I2(_000_[4]),
    .O(_074_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _211_ (
    .I0(Xin2[0]),
    .I1(Xin3[0]),
    .I2(Xin2[1]),
    .I3(Xin3[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_081_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _212_ (
    .I0(Xin0[0]),
    .I1(Xin1[0]),
    .I2(Xin0[1]),
    .I3(Xin1[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_081_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hca)
  ) _213_ (
    .I0(_093_[0]),
    .I1(_093_[1]),
    .I2(_000_[4]),
    .O(_074_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _214_ (
    .I0(Xin2[1]),
    .I1(Xin3[1]),
    .I2(Xin3[0]),
    .I3(Xin4[0]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_093_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _215_ (
    .I0(Xin0[1]),
    .I1(Xin1[1]),
    .I2(Xin1[0]),
    .I3(Xin2[0]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_093_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hd0)
  ) _216_ (
    .I0(_000_[4]),
    .I1(_097_[1]),
    .I2(_101_[2]),
    .O(_074_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _217_ (
    .I0(Xin3[0]),
    .I1(Xin4[0]),
    .I2(Xin3[1]),
    .I3(Xin4[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_097_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _218_ (
    .I0(Xin1[0]),
    .I1(Xin1[1]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _219_ (
    .I0(Xin2[0]),
    .I1(Xin2[1]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _220_ (
    .I0(_019_),
    .I1(_020_),
    .O(_101_[2]),
    .S(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hd0)
  ) _221_ (
    .I0(_000_[4]),
    .I1(_098_[1]),
    .I2(_102_[2]),
    .O(_074_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _222_ (
    .I0(Xin3[1]),
    .I1(Xin4[1]),
    .I2(Xin4[0]),
    .I3(Xin5[0]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_098_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _223_ (
    .I0(Xin1[1]),
    .I1(Xin2[0]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT4 #(
    .INIT(16'hf3f5)
  ) _224_ (
    .I0(Xin2[1]),
    .I1(Xin3[0]),
    .I2(_000_[4]),
    .I3(_000_[5]),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _225_ (
    .I0(_021_),
    .I1(_022_),
    .O(_102_[2]),
    .S(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _226_ (
    .I0(_099_[1]),
    .I1(_081_[1]),
    .I2(_000_[4]),
    .O(_074_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h00ff33330f0f5555)
  ) _227_ (
    .I0(Xin4[0]),
    .I1(Xin5[0]),
    .I2(Xin4[1]),
    .I3(Xin5[1]),
    .I4(_000_[5]),
    .I5(_000_[6]),
    .O(_099_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _228_ (
    .I0(_100_[0]),
    .I1(_093_[1]),
    .I2(_000_[4]),
    .O(_074_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd252654421)
  ) _229_ (
    .I0(Xin4[1]),
    .I1(Xin5[0]),
    .I2(Xin5[1]),
    .I3(_000_[5]),
    .I4(_000_[6]),
    .O(_100_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hac)
  ) _230_ (
    .I0(_097_[0]),
    .I1(_097_[1]),
    .I2(_000_[4]),
    .O(_074_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h3335)
  ) _231_ (
    .I0(Xin5[0]),
    .I1(Xin5[1]),
    .I2(_000_[5]),
    .I3(_000_[6]),
    .O(_097_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h5c)
  ) _232_ (
    .I0(Xin5[1]),
    .I1(_098_[1]),
    .I2(_000_[4]),
    .O(_074_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h5c)
  ) _233_ (
    .I0(Xin5[1]),
    .I1(_099_[1]),
    .I2(_000_[4]),
    .O(_074_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0f0f0f0f0f0f3355)
  ) _234_ (
    .I0(Xin4[1]),
    .I1(Xin5[0]),
    .I2(Xin5[1]),
    .I3(_000_[5]),
    .I4(_000_[6]),
    .I5(_000_[4]),
    .O(_074_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h5c)
  ) _235_ (
    .I0(Xin5[1]),
    .I1(_097_[0]),
    .I2(_000_[4]),
    .O(_074_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hccf0330f5555aaaa)
  ) _236_ (
    .I0(_079_[0]),
    .I1(_089_[1]),
    .I2(_089_[0]),
    .I3(_000_[4]),
    .I4(Xin0[0]),
    .I5(Ain5[1]),
    .O(_054_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hccf0330f5555aaaa)
  ) _237_ (
    .I0(_079_[1]),
    .I1(_087_[1]),
    .I2(_095_[0]),
    .I3(_000_[4]),
    .I4(Xin0[1]),
    .I5(Ain5[1]),
    .O(_054_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hcf0030ff5555aaaa)
  ) _238_ (
    .I0(_079_[2]),
    .I1(_083_[1]),
    .I2(_000_[4]),
    .I3(_088_[2]),
    .I4(Xin1[0]),
    .I5(Ain5[1]),
    .O(_054_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hcf0030ff5555aaaa)
  ) _239_ (
    .I0(_079_[3]),
    .I1(_080_[1]),
    .I2(_000_[4]),
    .I3(_080_[2]),
    .I4(Xin1[1]),
    .I5(Ain5[1]),
    .O(_054_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0cc0f335555aaaa)
  ) _240_ (
    .I0(_079_[4]),
    .I1(_089_[1]),
    .I2(_090_[0]),
    .I3(_000_[4]),
    .I4(Xin2[0]),
    .I5(Ain5[1]),
    .O(_054_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0cc0f335555aaaa)
  ) _241_ (
    .I0(_079_[5]),
    .I1(_087_[1]),
    .I2(_087_[0]),
    .I3(_000_[4]),
    .I4(Xin2[1]),
    .I5(Ain5[1]),
    .O(_054_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0cc0f335555aaaa)
  ) _242_ (
    .I0(_079_[6]),
    .I1(_083_[1]),
    .I2(_082_[1]),
    .I3(_000_[4]),
    .I4(Xin3[0]),
    .I5(Ain5[1]),
    .O(_054_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0fccf0335555aaaa)
  ) _243_ (
    .I0(_079_[7]),
    .I1(_080_[1]),
    .I2(Yin5[1]),
    .I3(_000_[4]),
    .I4(Xin3[1]),
    .I5(Ain5[1]),
    .O(_054_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _244_ (
    .I0(_077_[8]),
    .I1(_079_[8]),
    .I2(Ain5[1]),
    .I3(Xin4[0]),
    .O(_054_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _245_ (
    .I0(_052_[9]),
    .I1(Xin4[1]),
    .O(_054_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _246_ (
    .I0(_052_[10]),
    .I1(Xin5[0]),
    .O(_054_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _247_ (
    .I0(_052_[11]),
    .I1(Xin5[1]),
    .O(_054_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h330fccf0aaaa5555)
  ) _248_ (
    .I0(_076_[0]),
    .I1(_081_[1]),
    .I2(_081_[0]),
    .I3(_000_[4]),
    .I4(Yin0[0]),
    .I5(Ain5[1]),
    .O(_061_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h330fccf0aaaa5555)
  ) _249_ (
    .I0(_076_[1]),
    .I1(_093_[1]),
    .I2(_093_[0]),
    .I3(_000_[4]),
    .I4(Yin0[1]),
    .I5(Ain5[1]),
    .O(_061_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h30ffcf00aaaa5555)
  ) _250_ (
    .I0(_076_[2]),
    .I1(_097_[1]),
    .I2(_000_[4]),
    .I3(_101_[2]),
    .I4(Yin1[0]),
    .I5(Ain5[1]),
    .O(_061_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h30ffcf00aaaa5555)
  ) _251_ (
    .I0(_076_[3]),
    .I1(_098_[1]),
    .I2(_000_[4]),
    .I3(_102_[2]),
    .I4(Yin1[1]),
    .I5(Ain5[1]),
    .O(_061_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0f33f0ccaaaa5555)
  ) _252_ (
    .I0(_076_[4]),
    .I1(_081_[1]),
    .I2(_099_[1]),
    .I3(_000_[4]),
    .I4(Yin2[0]),
    .I5(Ain5[1]),
    .O(_061_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0f33f0ccaaaa5555)
  ) _253_ (
    .I0(_076_[5]),
    .I1(_093_[1]),
    .I2(_100_[0]),
    .I3(_000_[4]),
    .I4(Yin2[1]),
    .I5(Ain5[1]),
    .O(_061_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0f33f0ccaaaa5555)
  ) _254_ (
    .I0(_076_[6]),
    .I1(_097_[1]),
    .I2(_097_[0]),
    .I3(_000_[4]),
    .I4(Yin3[0]),
    .I5(Ain5[1]),
    .O(_061_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0330fccaaaa5555)
  ) _255_ (
    .I0(_076_[7]),
    .I1(_098_[1]),
    .I2(Xin5[1]),
    .I3(_000_[4]),
    .I4(Yin3[1]),
    .I5(Ain5[1]),
    .O(_061_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0330fccaaaa5555)
  ) _256_ (
    .I0(_076_[8]),
    .I1(_099_[1]),
    .I2(Xin5[1]),
    .I3(_000_[4]),
    .I4(Yin4[0]),
    .I5(Ain5[1]),
    .O(_061_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h5ca3)
  ) _257_ (
    .I0(_074_[9]),
    .I1(_076_[9]),
    .I2(Ain5[1]),
    .I3(Yin4[1]),
    .O(_061_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hf0330fccaaaa5555)
  ) _258_ (
    .I0(_076_[10]),
    .I1(_097_[0]),
    .I2(Xin5[1]),
    .I3(_000_[4]),
    .I4(Yin5[0]),
    .I5(Ain5[1]),
    .O(_061_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hac53)
  ) _259_ (
    .I0(Xin5[1]),
    .I1(_076_[11]),
    .I2(Ain5[1]),
    .I3(Yin5[1]),
    .O(_061_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _260_ (
    .I0(_071_[0]),
    .I1(_073_[0]),
    .I2(Ain5[1]),
    .I3(Ain0[0]),
    .O(_058_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _261_ (
    .I0(_071_[1]),
    .I1(_073_[1]),
    .I2(Ain5[1]),
    .I3(Ain0[1]),
    .O(_058_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _262_ (
    .I0(_071_[2]),
    .I1(_073_[2]),
    .I2(Ain5[1]),
    .I3(Ain1[0]),
    .O(_058_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _263_ (
    .I0(_056_[3]),
    .I1(Ain1[1]),
    .O(_058_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _264_ (
    .I0(_071_[4]),
    .I1(_073_[4]),
    .I2(Ain5[1]),
    .I3(Ain2[0]),
    .O(_058_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _265_ (
    .I0(_056_[5]),
    .I1(Ain2[1]),
    .O(_058_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _266_ (
    .I0(_056_[6]),
    .I1(Ain3[0]),
    .O(_058_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _267_ (
    .I0(_071_[7]),
    .I1(_073_[7]),
    .I2(Ain5[1]),
    .I3(Ain3[1]),
    .O(_058_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'ha35c)
  ) _268_ (
    .I0(_071_[8]),
    .I1(_073_[8]),
    .I2(Ain5[1]),
    .I3(Ain4[0]),
    .O(_058_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _269_ (
    .I0(_056_[9]),
    .I1(Ain4[1]),
    .O(_058_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _270_ (
    .I0(_056_[10]),
    .I1(Ain5[0]),
    .O(_058_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'he)
  ) _271_ (
    .I0(Ain5[1]),
    .I1(_073_[11]),
    .O(_058_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _272_ (
    .I(Yin5[1]),
    .O(_077_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _273_ (
    .I(Xin5[1]),
    .O(_074_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _274_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _275_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _276_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _277_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _278_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _279_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _280_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _281_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _282_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _283_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _284_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _285_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h10)
  ) _286_ (
    .I0(_071_[7]),
    .I1(_000_[6]),
    .I2(LoadCtl[6]),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _287_ (
    .CI(1'h0),
    .CO(_053_[3:0]),
    .CYINIT(1'h0),
    .DI(_052_[3:0]),
    .O(_055_[3:0]),
    .S(_054_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _288_ (
    .CI(_053_[3]),
    .CO(_053_[7:4]),
    .CYINIT(1'h0),
    .DI(_052_[7:4]),
    .O(_055_[7:4]),
    .S(_054_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:85.15-85.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _289_ (
    .CI(_053_[7]),
    .CO(_053_[11:8]),
    .CYINIT(1'h0),
    .DI(_052_[11:8]),
    .O(_055_[11:8]),
    .S(_054_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _290_ (
    .CI(1'h0),
    .CO(_057_[3:0]),
    .CYINIT(1'h0),
    .DI(_056_[3:0]),
    .O(_059_[3:0]),
    .S(_058_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _291_ (
    .CI(_057_[3]),
    .CO(_057_[7:4]),
    .CYINIT(1'h0),
    .DI(_056_[7:4]),
    .O(_059_[7:4]),
    .S(_058_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:87.15-87.28|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _292_ (
    .CI(_057_[7]),
    .CO(_057_[11:8]),
    .CYINIT(1'h0),
    .DI(_056_[11:8]),
    .O(_059_[11:8]),
    .S(_058_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:86.15-86.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _293_ (
    .CI(1'h0),
    .CO(_060_[3:0]),
    .CYINIT(1'h1),
    .DI({ Yin1, Yin0 }),
    .O(_062_[3:0]),
    .S(_061_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:86.15-86.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _294_ (
    .CI(_060_[3]),
    .CO(_060_[7:4]),
    .CYINIT(1'h0),
    .DI({ Yin3, Yin2 }),
    .O(_062_[7:4]),
    .S(_061_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:86.15-86.42|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _295_ (
    .CI(_060_[7]),
    .CO(_060_[11:8]),
    .CYINIT(1'h0),
    .DI({ Yin5, Yin4 }),
    .O(_062_[11:8]),
    .S(_061_[11:8])
  );
  BUFG _296_ (
    .I(_063_),
    .O(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:38.2-38.53|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _297_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_065_),
    .Q(_066_),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _298_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_044_),
    .Q(Ycalc[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _299_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_045_),
    .Q(Ycalc[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _300_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_046_),
    .Q(Ycalc[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _301_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_047_),
    .Q(Ycalc[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _302_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_048_),
    .Q(Ycalc[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _303_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_049_),
    .Q(Ycalc[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _304_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_050_),
    .Q(Ycalc[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _305_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_051_),
    .Q(Ycalc[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _306_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_042_),
    .Q(Ycalc[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _307_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_043_),
    .Q(Ycalc[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _308_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_062_[0]),
    .Q(Ycalc[0]),
    .R(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _309_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_062_[1]),
    .Q(Ycalc[1]),
    .S(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _310_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[0]),
    .Q(Xcalc[0]),
    .R(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _311_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[1]),
    .Q(Xcalc[1]),
    .S(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _312_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[2]),
    .Q(Xcalc[2]),
    .R(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _313_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[3]),
    .Q(Xcalc[3]),
    .S(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _314_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[4]),
    .Q(Xcalc[4]),
    .S(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _315_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[5]),
    .Q(Xcalc[5]),
    .R(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _316_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[6]),
    .Q(Xcalc[6]),
    .S(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _317_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[7]),
    .Q(Xcalc[7]),
    .S(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _318_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[8]),
    .Q(Xcalc[8]),
    .R(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _319_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[9]),
    .Q(Xcalc[9]),
    .R(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _320_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[10]),
    .Q(Xcalc[10]),
    .S(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _321_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_055_[11]),
    .Q(Xcalc[11]),
    .R(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _322_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[0]),
    .Q(Acalc[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _323_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[1]),
    .Q(Acalc[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _324_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[2]),
    .Q(Acalc[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _325_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[3]),
    .Q(Acalc[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _326_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[4]),
    .Q(Acalc[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _327_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[5]),
    .Q(Acalc[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _328_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[6]),
    .Q(Acalc[6]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _329_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[7]),
    .Q(Acalc[7]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _330_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[8]),
    .Q(Acalc[8]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _331_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[9]),
    .Q(Acalc[9]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _332_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[10]),
    .Q(Acalc[10]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:76.2-103.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _333_ (
    .C(_070_),
    .CE(LoadCtl[6]),
    .D(_059_[11]),
    .Q(Acalc[11]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _334_ (
    .C(_070_),
    .CE(_027_),
    .D(_068_[0]),
    .Q(Xin5[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _335_ (
    .C(_070_),
    .CE(_027_),
    .D(_068_[1]),
    .Q(Xin5[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _336_ (
    .C(_070_),
    .CE(_026_),
    .D(_068_[0]),
    .Q(Xin4[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _337_ (
    .C(_070_),
    .CE(_026_),
    .D(_068_[1]),
    .Q(Xin4[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _338_ (
    .C(_070_),
    .CE(_025_),
    .D(_068_[0]),
    .Q(Xin3[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _339_ (
    .C(_070_),
    .CE(_025_),
    .D(_068_[1]),
    .Q(Xin3[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _340_ (
    .C(_070_),
    .CE(_024_),
    .D(_068_[0]),
    .Q(Xin2[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _341_ (
    .C(_070_),
    .CE(_024_),
    .D(_068_[1]),
    .Q(Xin2[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _342_ (
    .C(_070_),
    .CE(_023_),
    .D(_068_[0]),
    .Q(Xin1[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _343_ (
    .C(_070_),
    .CE(_023_),
    .D(_068_[1]),
    .Q(Xin1[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _344_ (
    .C(_070_),
    .CE(LoadCtl[0]),
    .D(_068_[0]),
    .Q(Xin0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _345_ (
    .C(_070_),
    .CE(LoadCtl[0]),
    .D(_068_[1]),
    .Q(Xin0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _346_ (
    .C(_070_),
    .CE(_027_),
    .D(_069_[0]),
    .Q(Yin5[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _347_ (
    .C(_070_),
    .CE(_027_),
    .D(_069_[1]),
    .Q(Yin5[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _348_ (
    .C(_070_),
    .CE(_026_),
    .D(_069_[0]),
    .Q(Yin4[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _349_ (
    .C(_070_),
    .CE(_026_),
    .D(_069_[1]),
    .Q(Yin4[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _350_ (
    .C(_070_),
    .CE(_025_),
    .D(_069_[0]),
    .Q(Yin3[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _351_ (
    .C(_070_),
    .CE(_025_),
    .D(_069_[1]),
    .Q(Yin3[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _352_ (
    .C(_070_),
    .CE(_024_),
    .D(_069_[0]),
    .Q(Yin2[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _353_ (
    .C(_070_),
    .CE(_024_),
    .D(_069_[1]),
    .Q(Yin2[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _354_ (
    .C(_070_),
    .CE(_023_),
    .D(_069_[0]),
    .Q(Yin1[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _355_ (
    .C(_070_),
    .CE(_023_),
    .D(_069_[1]),
    .Q(Yin1[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _356_ (
    .C(_070_),
    .CE(LoadCtl[0]),
    .D(_069_[0]),
    .Q(Yin0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _357_ (
    .C(_070_),
    .CE(LoadCtl[0]),
    .D(_069_[1]),
    .Q(Yin0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _358_ (
    .C(_070_),
    .CE(_027_),
    .D(_064_[0]),
    .Q(Ain5[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _359_ (
    .C(_070_),
    .CE(_027_),
    .D(_064_[1]),
    .Q(Ain5[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _360_ (
    .C(_070_),
    .CE(_026_),
    .D(_064_[0]),
    .Q(Ain4[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _361_ (
    .C(_070_),
    .CE(_026_),
    .D(_064_[1]),
    .Q(Ain4[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _362_ (
    .C(_070_),
    .CE(_025_),
    .D(_064_[0]),
    .Q(Ain3[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _363_ (
    .C(_070_),
    .CE(_025_),
    .D(_064_[1]),
    .Q(Ain3[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _364_ (
    .C(_070_),
    .CE(_024_),
    .D(_064_[0]),
    .Q(Ain2[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _365_ (
    .C(_070_),
    .CE(_024_),
    .D(_064_[1]),
    .Q(Ain2[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _366_ (
    .C(_070_),
    .CE(_023_),
    .D(_064_[0]),
    .Q(Ain1[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _367_ (
    .C(_070_),
    .CE(_023_),
    .D(_064_[1]),
    .Q(Ain1[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _368_ (
    .C(_070_),
    .CE(LoadCtl[0]),
    .D(_064_[0]),
    .Q(Ain0[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:45.2-52.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _369_ (
    .C(_070_),
    .CE(LoadCtl[0]),
    .D(_064_[1]),
    .Q(Ain0[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _370_ (
    .C(_070_),
    .CE(1'h1),
    .D(_067_),
    .Q(LoadCtl[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _371_ (
    .C(_070_),
    .CE(1'h1),
    .D(LoadCtl[0]),
    .Q(LoadCtl[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _372_ (
    .C(_070_),
    .CE(1'h1),
    .D(LoadCtl[1]),
    .Q(LoadCtl[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _373_ (
    .C(_070_),
    .CE(1'h1),
    .D(LoadCtl[2]),
    .Q(LoadCtl[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _374_ (
    .C(_070_),
    .CE(1'h1),
    .D(LoadCtl[3]),
    .Q(LoadCtl[4]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _375_ (
    .C(_070_),
    .CE(1'h1),
    .D(LoadCtl[4]),
    .Q(LoadCtl[5]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/cordic_element.v:29.5-34.8|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _376_ (
    .C(_070_),
    .CE(1'h1),
    .D(LoadCtl[5]),
    .Q(LoadCtl[6]),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF _377_ (
    .I(Ain[0]),
    .O(_064_[0])
  );
  (* keep = 32'd1 *)
  IBUF _378_ (
    .I(Ain[1]),
    .O(_064_[1])
  );
  (* keep = 32'd1 *)
  OBUF _379_ (
    .I(A_[0]),
    .O(Aout[0])
  );
  (* keep = 32'd1 *)
  OBUF _380_ (
    .I(A_[1]),
    .O(Aout[1])
  );
  (* keep = 32'd1 *)
  IBUF _381_ (
    .I(ISin),
    .O(_065_)
  );
  (* keep = 32'd1 *)
  OBUF _382_ (
    .I(_066_),
    .O(ISout)
  );
  (* keep = 32'd1 *)
  IBUF _383_ (
    .I(Rdy),
    .O(_067_)
  );
  (* keep = 32'd1 *)
  IBUF _384_ (
    .I(Stg[0]),
    .O(_000_[5])
  );
  (* keep = 32'd1 *)
  IBUF _385_ (
    .I(Stg[1]),
    .O(_000_[6])
  );
  (* keep = 32'd1 *)
  IBUF _386_ (
    .I(Stg[2]),
    .O(_000_[4])
  );
  (* keep = 32'd1 *)
  OBUF _387_ (
    .I(LoadCtl[6]),
    .O(Vld)
  );
  (* keep = 32'd1 *)
  IBUF _388_ (
    .I(Xin[0]),
    .O(_068_[0])
  );
  (* keep = 32'd1 *)
  IBUF _389_ (
    .I(Xin[1]),
    .O(_068_[1])
  );
  (* keep = 32'd1 *)
  OBUF _390_ (
    .I(X_[0]),
    .O(Xout[0])
  );
  (* keep = 32'd1 *)
  OBUF _391_ (
    .I(X_[1]),
    .O(Xout[1])
  );
  (* keep = 32'd1 *)
  IBUF _392_ (
    .I(Yin[0]),
    .O(_069_[0])
  );
  (* keep = 32'd1 *)
  IBUF _393_ (
    .I(Yin[1]),
    .O(_069_[1])
  );
  (* keep = 32'd1 *)
  OBUF _394_ (
    .I(Y_[0]),
    .O(Yout[0])
  );
  (* keep = 32'd1 *)
  OBUF _395_ (
    .I(Y_[1]),
    .O(Yout[1])
  );
  (* keep = 32'd1 *)
  IBUF _396_ (
    .I(clk),
    .O(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _397_ (
    .CI(1'h0),
    .CO(_072_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_073_[3:0]),
    .S(_071_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _398_ (
    .CI(_072_[3]),
    .CO(_072_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_073_[7:4]),
    .S(_071_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _399_ (
    .CI(_072_[7]),
    .CO(_072_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_073_[11:8]),
    .S({ 3'h7, _071_[8] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _400_ (
    .CI(1'h0),
    .CO(_075_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_076_[3:0]),
    .S(_074_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _401_ (
    .CI(_075_[3]),
    .CO(_075_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_076_[7:4]),
    .S(_074_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _402_ (
    .CI(_075_[7]),
    .CO(_075_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_076_[11:8]),
    .S(_074_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _403_ (
    .CI(1'h0),
    .CO(_078_[3:0]),
    .CYINIT(1'h1),
    .DI(4'h0),
    .O(_079_[3:0]),
    .S(_077_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _404_ (
    .CI(_078_[3]),
    .CO(_078_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_079_[7:4]),
    .S(_077_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _405_ (
    .CI(_078_[7]),
    .CO(_078_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _079_[11], _014_[1], _007_[2], _079_[8] }),
    .S(_077_[11:8])
  );
  assign _081_[2] = _000_[4];
  assign _092_[1] = _085_[0];
  assign _086_[1] = _085_[0];
  assign { _083_[4:2], _083_[0] } = { Ain5[1], _000_[4], _079_[6], _082_[1] };
  assign _101_[1:0] = { _097_[1], _000_[4] };
  assign { _084_[5], _084_[2], _084_[0] } = { LoadCtl[0], Xcalc[0], Xcalc[4] };
  assign _000_[3:0] = { Yin2[1], Yin1[1], Yin2[0], Yin1[0] };
  assign _088_[1:0] = { _083_[1], _000_[4] };
  assign _093_[2] = _000_[4];
  assign { _014_[6:2], _014_[0] } = { Ain5[1], Yin5[1], _000_[4], _000_[6:5], Yin5[0] };
  assign _094_[1] = _085_[0];
  assign _096_[1] = _085_[0];
  assign _102_[1:0] = { _098_[1], _000_[4] };
  assign _089_[4:2] = { Ain5[1], _000_[4], _079_[0] };
  assign { _007_[7:3], _007_[1:0] } = { Ain5[1], _000_[4], _000_[6:5], Yin5, Yin4[1] };
  assign _097_[2] = _000_[4];
  assign _100_[2:1] = { _000_[4], _093_[1] };
  assign { _082_[2], _082_[0] } = { _000_[4], Yin5[1] };
  assign _091_[1] = _085_[0];
  assign { _098_[2], _098_[0] } = { _000_[4], Xin5[1] };
  assign _087_[4:2] = { Ain5[1], _000_[4], _079_[5] };
  assign { _099_[2], _099_[0] } = { _000_[4], Xin5[1] };
  assign _085_[1] = LoadCtl[3];
  assign _090_[2:1] = { _000_[4], _089_[1] };
  assign _080_[0] = _000_[4];
  assign _095_[4:1] = { Ain5[1], _000_[4], _079_[1], _087_[1] };
  assign _071_[11:9] = 3'h7;
  assign _079_[10:9] = { _014_[1], _007_[2] };
  assign Ain12b = { Ain5, Ain4, Ain3, Ain2, Ain1, Ain0 };
  assign Xin12b = { Xin5, Xin4, Xin3, Xin2, Xin1, Xin0 };
  assign Yin12b = { Yin5, Yin4, Yin3, Yin2, Yin1, Yin0 };
  assign atan[11:9] = 3'h0;
  assign atan0 = 12'h1ff;
  assign atan1 = 12'h12d;
  assign atan2 = 12'h09f;
  assign atan3 = 12'h050;
  assign atan4 = 12'h028;
  assign atan5 = 12'h013;
  assign atan6 = 12'h009;
  assign atan7 = 12'h004;
  assign oneOverK = 12'h4da;
endmodule
