/* Generated by Yosys 0.50+0 (git sha1 6f9c515a2, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */
(* blackbox *)
(* top =  1  *)
(* src = "./../../source/phase_accumulator.v:1.1-66.10" *)
module phase_accumulator(clk, En, FCW, Vld, Aout, ISout);
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _000_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _001_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _002_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _003_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.12-78.14" *)
  wire _004_;
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:78.16-78.18" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 19" *)
  wire [19:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [19:0] _049_;
  (* force_downto = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [19:0] _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire _054_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _055_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _056_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _062_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _063_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _064_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _066_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _067_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _068_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _072_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _074_;
  (* src = "./../../source/phase_accumulator.v:6.20-6.24" *)
  output [1:0] Aout;
  wire [1:0] Aout;
  (* src = "./../../source/phase_accumulator.v:24.13-24.17" *)
  wire [11:0] Atmp;
  (* src = "./../../source/phase_accumulator.v:3.10-3.12" *)
  input En;
  wire En;
  (* src = "./../../source/phase_accumulator.v:4.17-4.20" *)
  input [19:0] FCW;
  wire [19:0] FCW;
  (* src = "./../../source/phase_accumulator.v:7.15-7.20" *)
  output ISout;
  wire ISout;
  (* src = "./../../source/phase_accumulator.v:11.21-11.27" *)
  wire [6:0] RdyCtl;
  (* src = "./../../source/phase_accumulator.v:5.12-5.15" *)
  output Vld;
  wire Vld;
  (* src = "./../../source/phase_accumulator.v:23.13-23.20" *)
  wire [19:0] acc_reg;
  (* src = "./../../source/phase_accumulator.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _075_ (
    .I0(Atmp[4]),
    .I1(_000_[1]),
    .I2(Atmp[2]),
    .I3(RdyCtl[2]),
    .I4(RdyCtl[1]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _076_ (
    .I0(Atmp[0]),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _077_ (
    .I0(_001_),
    .I1(_002_),
    .O(_045_),
    .S(RdyCtl[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _078_ (
    .I0(Atmp[8]),
    .I1(Atmp[10]),
    .I2(Atmp[6]),
    .I3(RdyCtl[4]),
    .I4(RdyCtl[3]),
    .O(_000_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:79.45-79.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT5 #(
    .INIT(32'd4042304204)
  ) _079_ (
    .I0(Atmp[5]),
    .I1(_003_[1]),
    .I2(Atmp[3]),
    .I3(RdyCtl[2]),
    .I4(RdyCtl[1]),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:80.45-80.70|/usr/local/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT1 #(
    .INIT(2'h2)
  ) _080_ (
    .I0(Atmp[1]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _081_ (
    .I0(_004_),
    .I1(_005_),
    .O(_046_),
    .S(RdyCtl[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd4042312874)
  ) _082_ (
    .I0(Atmp[11]),
    .I1(Atmp[9]),
    .I2(Atmp[7]),
    .I3(RdyCtl[4]),
    .I4(RdyCtl[3]),
    .O(_003_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _083_ (
    .I0(acc_reg[19]),
    .I1(acc_reg[18]),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _084_ (
    .I0(_074_[0]),
    .I1(acc_reg[0]),
    .O(_049_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _085_ (
    .I0(_073_[0]),
    .I1(acc_reg[1]),
    .O(_049_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _086_ (
    .I0(_072_[0]),
    .I1(acc_reg[2]),
    .O(_049_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _087_ (
    .I0(_071_[0]),
    .I1(acc_reg[3]),
    .O(_049_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _088_ (
    .I0(_070_[0]),
    .I1(acc_reg[4]),
    .O(_049_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _089_ (
    .I0(_069_[0]),
    .I1(acc_reg[5]),
    .O(_049_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _090_ (
    .I0(_068_[0]),
    .I1(acc_reg[6]),
    .O(_049_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _091_ (
    .I0(_067_[0]),
    .I1(acc_reg[7]),
    .O(_049_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _092_ (
    .I0(_066_[0]),
    .I1(acc_reg[8]),
    .O(_049_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _093_ (
    .I0(_065_[0]),
    .I1(acc_reg[9]),
    .O(_049_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _094_ (
    .I0(_064_[0]),
    .I1(acc_reg[10]),
    .O(_049_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _095_ (
    .I0(_063_[0]),
    .I1(acc_reg[11]),
    .O(_049_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _096_ (
    .I0(_062_[0]),
    .I1(acc_reg[12]),
    .O(_049_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _097_ (
    .I0(_061_[0]),
    .I1(acc_reg[13]),
    .O(_049_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _098_ (
    .I0(_060_[0]),
    .I1(acc_reg[14]),
    .O(_049_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _099_ (
    .I0(_059_[0]),
    .I1(acc_reg[15]),
    .O(_049_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _100_ (
    .I0(_058_[0]),
    .I1(acc_reg[16]),
    .O(_049_[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _101_ (
    .I0(_057_[0]),
    .I1(acc_reg[17]),
    .O(_049_[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _102_ (
    .I0(acc_reg[18]),
    .I1(_056_[1]),
    .O(_049_[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _103_ (
    .I0(acc_reg[19]),
    .I1(_055_[1]),
    .O(_049_[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _104_ (
    .I(_054_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _105_ (
    .I(_054_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _106_ (
    .I(_054_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _107_ (
    .I(_054_),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _108_ (
    .I(_054_),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _109_ (
    .I(_054_),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _110_ (
    .I(_054_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _111_ (
    .I(_054_),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _112_ (
    .I(_054_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _113_ (
    .I(_054_),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _114_ (
    .I(_054_),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _115_ (
    .I(_054_),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _116_ (
    .I(_054_),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _117_ (
    .I(_054_),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _118_ (
    .I(_054_),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _119_ (
    .I(_054_),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _120_ (
    .I(_054_),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _121_ (
    .I(_054_),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _122_ (
    .I(_054_),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _123_ (
    .I(_054_),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _124_ (
    .I(_054_),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _125_ (
    .I(_054_),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _126_ (
    .I(_054_),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _127_ (
    .I(_054_),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _128_ (
    .I(_054_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _129_ (
    .I(_054_),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _130_ (
    .I(_054_),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _131_ (
    .I(_054_),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _132_ (
    .I(_054_),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _133_ (
    .I(_054_),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _134_ (
    .I(_054_),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _135_ (
    .I(_054_),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _136_ (
    .I(_054_),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _137_ (
    .I(_054_),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _138_ (
    .I(_054_),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _139_ (
    .I(_054_),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _140_ (
    .I(_054_),
    .O(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _141_ (
    .I(_054_),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _142_ (
    .I(_054_),
    .O(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _143_ (
    .CI(1'h0),
    .CO(_048_[3:0]),
    .CYINIT(1'h0),
    .DI({ _071_[0], _072_[0], _073_[0], _074_[0] }),
    .O(_050_[3:0]),
    .S(_049_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _144_ (
    .CI(_048_[3]),
    .CO(_048_[7:4]),
    .CYINIT(1'h0),
    .DI({ _067_[0], _068_[0], _069_[0], _070_[0] }),
    .O(_050_[7:4]),
    .S(_049_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _145_ (
    .CI(_048_[7]),
    .CO(_048_[11:8]),
    .CYINIT(1'h0),
    .DI({ _063_[0], _064_[0], _065_[0], _066_[0] }),
    .O(_050_[11:8]),
    .S(_049_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _146_ (
    .CI(_048_[11]),
    .CO(_048_[15:12]),
    .CYINIT(1'h0),
    .DI({ _059_[0], _060_[0], _061_[0], _062_[0] }),
    .O(_050_[15:12]),
    .S(_049_[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:34.16-34.29|/usr/local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _147_ (
    .CI(_048_[15]),
    .CO(_048_[19:16]),
    .CYINIT(1'h0),
    .DI({ _055_[1], _056_[1], _057_[0], _058_[0] }),
    .O(_050_[19:16]),
    .S(_049_[19:16])
  );
  BUFG _148_ (
    .I(_051_),
    .O(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _149_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[6]),
    .Q(RdyCtl[0]),
    .R(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _150_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[0]),
    .Q(RdyCtl[1]),
    .R(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _151_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[1]),
    .Q(RdyCtl[2]),
    .R(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _152_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[2]),
    .Q(RdyCtl[3]),
    .R(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _153_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[3]),
    .Q(RdyCtl[4]),
    .R(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _154_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[4]),
    .Q(RdyCtl[5]),
    .S(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:12.2-19.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _155_ (
    .C(_053_),
    .CE(1'h1),
    .D(RdyCtl[5]),
    .Q(RdyCtl[6]),
    .R(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _156_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[0]),
    .Q(acc_reg[0]),
    .R(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _157_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[1]),
    .Q(acc_reg[1]),
    .R(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _158_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[2]),
    .Q(acc_reg[2]),
    .R(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _159_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[3]),
    .Q(acc_reg[3]),
    .R(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _160_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[4]),
    .Q(acc_reg[4]),
    .R(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _161_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[5]),
    .Q(acc_reg[5]),
    .R(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _162_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[6]),
    .Q(acc_reg[6]),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _163_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[7]),
    .Q(acc_reg[7]),
    .R(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _164_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[8]),
    .Q(acc_reg[8]),
    .R(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _165_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[9]),
    .Q(acc_reg[9]),
    .R(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _166_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[10]),
    .Q(acc_reg[10]),
    .R(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _167_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[11]),
    .Q(acc_reg[11]),
    .R(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _168_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[12]),
    .Q(acc_reg[12]),
    .R(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _169_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[13]),
    .Q(acc_reg[13]),
    .R(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _170_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[14]),
    .Q(acc_reg[14]),
    .R(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _171_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[15]),
    .Q(acc_reg[15]),
    .R(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _172_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[16]),
    .Q(acc_reg[16]),
    .R(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _173_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[17]),
    .Q(acc_reg[17]),
    .R(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _174_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[18]),
    .Q(acc_reg[18]),
    .R(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _175_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(_050_[19]),
    .Q(acc_reg[19]),
    .R(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _176_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[8]),
    .Q(Atmp[0]),
    .R(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _177_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[9]),
    .Q(Atmp[1]),
    .R(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _178_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[10]),
    .Q(Atmp[2]),
    .R(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _179_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[11]),
    .Q(Atmp[3]),
    .R(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _180_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[12]),
    .Q(Atmp[4]),
    .R(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _181_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[13]),
    .Q(Atmp[5]),
    .R(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _182_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[14]),
    .Q(Atmp[6]),
    .R(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _183_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[15]),
    .Q(Atmp[7]),
    .R(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _184_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[16]),
    .Q(Atmp[8]),
    .R(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _185_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[17]),
    .Q(Atmp[9]),
    .R(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _186_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[18]),
    .Q(Atmp[10]),
    .R(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:26.2-45.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _187_ (
    .C(_053_),
    .CE(RdyCtl[6]),
    .D(acc_reg[18]),
    .Q(Atmp[11]),
    .R(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./../../source/phase_accumulator.v:48.2-53.5|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _188_ (
    .C(_053_),
    .CE(RdyCtl[5]),
    .D(_047_),
    .Q(_052_),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  OBUF _189_ (
    .I(_045_),
    .O(Aout[0])
  );
  (* keep = 32'd1 *)
  OBUF _190_ (
    .I(_046_),
    .O(Aout[1])
  );
  (* keep = 32'd1 *)
  IBUF _191_ (
    .I(En),
    .O(_054_)
  );
  (* keep = 32'd1 *)
  IBUF _192_ (
    .I(FCW[0]),
    .O(_074_[0])
  );
  (* keep = 32'd1 *)
  IBUF _193_ (
    .I(FCW[1]),
    .O(_073_[0])
  );
  (* keep = 32'd1 *)
  IBUF _194_ (
    .I(FCW[10]),
    .O(_064_[0])
  );
  (* keep = 32'd1 *)
  IBUF _195_ (
    .I(FCW[11]),
    .O(_063_[0])
  );
  (* keep = 32'd1 *)
  IBUF _196_ (
    .I(FCW[12]),
    .O(_062_[0])
  );
  (* keep = 32'd1 *)
  IBUF _197_ (
    .I(FCW[13]),
    .O(_061_[0])
  );
  (* keep = 32'd1 *)
  IBUF _198_ (
    .I(FCW[14]),
    .O(_060_[0])
  );
  (* keep = 32'd1 *)
  IBUF _199_ (
    .I(FCW[15]),
    .O(_059_[0])
  );
  (* keep = 32'd1 *)
  IBUF _200_ (
    .I(FCW[16]),
    .O(_058_[0])
  );
  (* keep = 32'd1 *)
  IBUF _201_ (
    .I(FCW[17]),
    .O(_057_[0])
  );
  (* keep = 32'd1 *)
  IBUF _202_ (
    .I(FCW[18]),
    .O(_056_[1])
  );
  (* keep = 32'd1 *)
  IBUF _203_ (
    .I(FCW[19]),
    .O(_055_[1])
  );
  (* keep = 32'd1 *)
  IBUF _204_ (
    .I(FCW[2]),
    .O(_072_[0])
  );
  (* keep = 32'd1 *)
  IBUF _205_ (
    .I(FCW[3]),
    .O(_071_[0])
  );
  (* keep = 32'd1 *)
  IBUF _206_ (
    .I(FCW[4]),
    .O(_070_[0])
  );
  (* keep = 32'd1 *)
  IBUF _207_ (
    .I(FCW[5]),
    .O(_069_[0])
  );
  (* keep = 32'd1 *)
  IBUF _208_ (
    .I(FCW[6]),
    .O(_068_[0])
  );
  (* keep = 32'd1 *)
  IBUF _209_ (
    .I(FCW[7]),
    .O(_067_[0])
  );
  (* keep = 32'd1 *)
  IBUF _210_ (
    .I(FCW[8]),
    .O(_066_[0])
  );
  (* keep = 32'd1 *)
  IBUF _211_ (
    .I(FCW[9]),
    .O(_065_[0])
  );
  (* keep = 32'd1 *)
  OBUF _212_ (
    .I(_052_),
    .O(ISout)
  );
  (* keep = 32'd1 *)
  OBUF _213_ (
    .I(RdyCtl[6]),
    .O(Vld)
  );
  (* keep = 32'd1 *)
  IBUF _214_ (
    .I(clk),
    .O(_051_)
  );
  assign _072_[1] = acc_reg[2];
  assign _063_[1] = acc_reg[11];
  assign _073_[1] = acc_reg[1];
  assign _056_[0] = acc_reg[18];
  assign _074_[1] = acc_reg[0];
  assign _064_[1] = acc_reg[10];
  assign _059_[1] = acc_reg[15];
  assign _065_[1] = acc_reg[9];
  assign _055_[0] = acc_reg[19];
  assign _066_[1] = acc_reg[8];
  assign { _003_[6:2], _003_[0] } = { RdyCtl[0], RdyCtl[1], RdyCtl[2], Atmp[1], Atmp[3], Atmp[5] };
  assign _060_[1] = acc_reg[14];
  assign _067_[1] = acc_reg[7];
  assign _057_[1] = acc_reg[17];
  assign { _000_[6:2], _000_[0] } = { RdyCtl[0], RdyCtl[1], RdyCtl[2], Atmp[0], Atmp[2], Atmp[4] };
  assign _068_[1] = acc_reg[6];
  assign _061_[1] = acc_reg[13];
  assign _069_[1] = acc_reg[5];
  assign _070_[1] = acc_reg[4];
  assign _062_[1] = acc_reg[12];
  assign _071_[1] = acc_reg[3];
  assign _058_[1] = acc_reg[16];
endmodule
