/* Generated by Yosys 0.50+0 (git sha1 6f9c515a2, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:1.1-68.10" *)
module output_terminal(clk, selXY, selSign, Xin, Yin, Dout, Rdy, Vld, ISin);
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:8.18-8.22" *)
  output [11:0] Dout;
  wire [11:0] Dout;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:11.10-11.14" *)
  input ISin;
  wire ISin;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:25.6-25.11" *)
  wire ISreg;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:16.21-16.28" *)
  wire [6:0] LoadCtl;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:9.10-9.13" *)
  input Rdy;
  wire Rdy;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:10.11-10.14" *)
  output Vld;
  wire Vld;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:51.14-51.19" *)
  wire [11:0] Xcalc;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:6.16-6.19" *)
  input [1:0] Xin;
  wire [1:0] Xin;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:29.42-29.46" *)
  wire [1:0] Xin0;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:29.36-29.40" *)
  wire [1:0] Xin1;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:49.14-49.20" *)
  wire [11:0] Xin12b;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:51.21-51.26" *)
  wire [11:0] Ycalc;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:7.16-7.19" *)
  input [1:0] Yin;
  wire [1:0] Yin;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:30.42-30.46" *)
  wire [1:0] Yin0;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:30.36-30.40" *)
  wire [1:0] Yin1;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:50.14-50.20" *)
  wire [11:0] Yin12b;
  wire _0_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _10_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _11_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _12_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _13_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _14_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _15_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _16_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _17_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _18_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _19_;
  wire _1_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _20_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _21_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _22_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _23_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _24_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _25_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _26_;
  wire _270_;
  wire _271_;
  wire [11:0] _272_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _88_;
  wire _89_;
  wire _8_;
  wire _90_;
  wire _91_;
  wire _92_;
  wire _93_;
  wire _94_;
  wire _95_;
  wire _96_;
  wire _97_;
  wire _98_;
  wire _99_;
  wire _9_;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:5.10-5.17" *)
  input selSign;
  wire selSign;
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:4.10-4.15" *)
  input selXY;
  wire selXY;
  INVX1 _273_ (
    .A(Ycalc[0]),
    .Y(_49_)
  );
  NAND2X1 _274_ (
    .A(Xcalc[0]),
    .B(selXY),
    .Y(_50_)
  );
  OAI21X1 _275_ (
    .A(selXY),
    .B(_49_),
    .C(_50_),
    .Y(_272_[0])
  );
  INVX1 _276_ (
    .A(Ycalc[1]),
    .Y(_51_)
  );
  NAND2X1 _277_ (
    .A(selXY),
    .B(Xcalc[1]),
    .Y(_52_)
  );
  OAI21X1 _278_ (
    .A(selXY),
    .B(_51_),
    .C(_52_),
    .Y(_272_[1])
  );
  INVX1 _279_ (
    .A(Ycalc[2]),
    .Y(_53_)
  );
  NAND2X1 _280_ (
    .A(selXY),
    .B(Xcalc[2]),
    .Y(_54_)
  );
  OAI21X1 _281_ (
    .A(selXY),
    .B(_53_),
    .C(_54_),
    .Y(_272_[2])
  );
  INVX1 _282_ (
    .A(Ycalc[3]),
    .Y(_55_)
  );
  NAND2X1 _283_ (
    .A(selXY),
    .B(Xcalc[3]),
    .Y(_56_)
  );
  OAI21X1 _284_ (
    .A(selXY),
    .B(_55_),
    .C(_56_),
    .Y(_272_[3])
  );
  INVX1 _285_ (
    .A(Ycalc[4]),
    .Y(_57_)
  );
  NAND2X1 _286_ (
    .A(selXY),
    .B(Xcalc[4]),
    .Y(_58_)
  );
  OAI21X1 _287_ (
    .A(selXY),
    .B(_57_),
    .C(_58_),
    .Y(_272_[4])
  );
  INVX1 _288_ (
    .A(Ycalc[5]),
    .Y(_59_)
  );
  NAND2X1 _289_ (
    .A(selXY),
    .B(Xcalc[5]),
    .Y(_60_)
  );
  OAI21X1 _290_ (
    .A(selXY),
    .B(_59_),
    .C(_60_),
    .Y(_272_[5])
  );
  INVX1 _291_ (
    .A(Ycalc[6]),
    .Y(_61_)
  );
  NAND2X1 _292_ (
    .A(selXY),
    .B(Xcalc[6]),
    .Y(_62_)
  );
  OAI21X1 _293_ (
    .A(selXY),
    .B(_61_),
    .C(_62_),
    .Y(_272_[6])
  );
  INVX1 _294_ (
    .A(Ycalc[7]),
    .Y(_63_)
  );
  NAND2X1 _295_ (
    .A(selXY),
    .B(Xcalc[7]),
    .Y(_64_)
  );
  OAI21X1 _296_ (
    .A(selXY),
    .B(_63_),
    .C(_64_),
    .Y(_272_[7])
  );
  INVX1 _297_ (
    .A(Ycalc[8]),
    .Y(_65_)
  );
  NAND2X1 _298_ (
    .A(selXY),
    .B(Xcalc[8]),
    .Y(_66_)
  );
  OAI21X1 _299_ (
    .A(selXY),
    .B(_65_),
    .C(_66_),
    .Y(_272_[8])
  );
  INVX1 _300_ (
    .A(Ycalc[9]),
    .Y(_67_)
  );
  NAND2X1 _301_ (
    .A(selXY),
    .B(Xcalc[9]),
    .Y(_68_)
  );
  OAI21X1 _302_ (
    .A(selXY),
    .B(_67_),
    .C(_68_),
    .Y(_272_[9])
  );
  INVX1 _303_ (
    .A(Ycalc[10]),
    .Y(_69_)
  );
  NAND2X1 _304_ (
    .A(selXY),
    .B(Xcalc[10]),
    .Y(_70_)
  );
  OAI21X1 _305_ (
    .A(selXY),
    .B(_69_),
    .C(_70_),
    .Y(_272_[10])
  );
  INVX1 _306_ (
    .A(Ycalc[11]),
    .Y(_71_)
  );
  NAND2X1 _307_ (
    .A(selXY),
    .B(Xcalc[11]),
    .Y(_72_)
  );
  OAI21X1 _308_ (
    .A(selXY),
    .B(_71_),
    .C(_72_),
    .Y(_272_[11])
  );
  INVX1 _309_ (
    .A(Yin[1]),
    .Y(_73_)
  );
  INVX1 _310_ (
    .A(LoadCtl[2]),
    .Y(_74_)
  );
  NOR2X1 _311_ (
    .A(LoadCtl[0]),
    .B(LoadCtl[1]),
    .Y(_75_)
  );
  NAND3X1 _312_ (
    .A(_74_),
    .B(LoadCtl[3]),
    .C(_75_),
    .Y(_76_)
  );
  NAND2X1 _313_ (
    .A(Yin12b[7]),
    .B(_76_),
    .Y(_77_)
  );
  OAI21X1 _314_ (
    .A(_73_),
    .B(_76_),
    .C(_77_),
    .Y(_1_)
  );
  INVX1 _315_ (
    .A(Yin12b[4]),
    .Y(_78_)
  );
  INVX1 _316_ (
    .A(_75_),
    .Y(_79_)
  );
  NOR2X1 _317_ (
    .A(_74_),
    .B(_79_),
    .Y(_80_)
  );
  NAND2X1 _318_ (
    .A(Yin[0]),
    .B(_80_),
    .Y(_81_)
  );
  OAI21X1 _319_ (
    .A(_78_),
    .B(_80_),
    .C(_81_),
    .Y(_2_)
  );
  INVX1 _320_ (
    .A(Yin12b[5]),
    .Y(_82_)
  );
  NAND2X1 _321_ (
    .A(Yin[1]),
    .B(_80_),
    .Y(_83_)
  );
  OAI21X1 _322_ (
    .A(_82_),
    .B(_80_),
    .C(_83_),
    .Y(_3_)
  );
  INVX1 _323_ (
    .A(Yin[0]),
    .Y(_84_)
  );
  INVX1 _324_ (
    .A(LoadCtl[1]),
    .Y(_85_)
  );
  OR2X2 _325_ (
    .A(_85_),
    .B(LoadCtl[0]),
    .Y(_86_)
  );
  OAI21X1 _326_ (
    .A(LoadCtl[0]),
    .B(_85_),
    .C(Yin1[0]),
    .Y(_87_)
  );
  OAI21X1 _327_ (
    .A(_84_),
    .B(_86_),
    .C(_87_),
    .Y(_4_)
  );
  OAI21X1 _328_ (
    .A(LoadCtl[0]),
    .B(_85_),
    .C(Yin1[1]),
    .Y(_88_)
  );
  OAI21X1 _329_ (
    .A(_73_),
    .B(_86_),
    .C(_88_),
    .Y(_5_)
  );
  INVX1 _330_ (
    .A(Yin0[0]),
    .Y(_89_)
  );
  NAND2X1 _331_ (
    .A(LoadCtl[0]),
    .B(Yin[0]),
    .Y(_90_)
  );
  OAI21X1 _332_ (
    .A(LoadCtl[0]),
    .B(_89_),
    .C(_90_),
    .Y(_6_)
  );
  INVX1 _333_ (
    .A(Yin0[1]),
    .Y(_91_)
  );
  NAND2X1 _334_ (
    .A(LoadCtl[0]),
    .B(Yin[1]),
    .Y(_92_)
  );
  OAI21X1 _335_ (
    .A(LoadCtl[0]),
    .B(_91_),
    .C(_92_),
    .Y(_7_)
  );
  INVX1 _336_ (
    .A(ISreg),
    .Y(_93_)
  );
  NAND2X1 _337_ (
    .A(ISin),
    .B(LoadCtl[6]),
    .Y(_94_)
  );
  OAI21X1 _338_ (
    .A(LoadCtl[6]),
    .B(_93_),
    .C(_94_),
    .Y(_8_)
  );
  INVX1 _339_ (
    .A(Xin0[0]),
    .Y(_95_)
  );
  INVX1 _340_ (
    .A(LoadCtl[6]),
    .Y(_96_)
  );
  NAND2X1 _341_ (
    .A(Xcalc[0]),
    .B(_96_),
    .Y(_97_)
  );
  OAI21X1 _342_ (
    .A(_95_),
    .B(_96_),
    .C(_97_),
    .Y(_9_)
  );
  NAND3X1 _343_ (
    .A(ISreg),
    .B(Xin0[0]),
    .C(Xin0[1]),
    .Y(_98_)
  );
  INVX1 _344_ (
    .A(Xin0[1]),
    .Y(_99_)
  );
  OAI21X1 _345_ (
    .A(_93_),
    .B(_95_),
    .C(_99_),
    .Y(_100_)
  );
  NAND2X1 _346_ (
    .A(_98_),
    .B(_100_),
    .Y(_101_)
  );
  NAND2X1 _347_ (
    .A(Xcalc[1]),
    .B(_96_),
    .Y(_102_)
  );
  OAI21X1 _348_ (
    .A(_96_),
    .B(_101_),
    .C(_102_),
    .Y(_10_)
  );
  INVX1 _349_ (
    .A(Xin1[0]),
    .Y(_103_)
  );
  OAI21X1 _350_ (
    .A(Xin0[0]),
    .B(Xin0[1]),
    .C(ISreg),
    .Y(_104_)
  );
  OR2X2 _351_ (
    .A(_104_),
    .B(_103_),
    .Y(_105_)
  );
  NOR2X1 _352_ (
    .A(Xin0[0]),
    .B(Xin0[1]),
    .Y(_106_)
  );
  OAI21X1 _353_ (
    .A(_93_),
    .B(_106_),
    .C(_103_),
    .Y(_107_)
  );
  NAND2X1 _354_ (
    .A(_107_),
    .B(_105_),
    .Y(_108_)
  );
  NAND2X1 _355_ (
    .A(Xcalc[2]),
    .B(_96_),
    .Y(_109_)
  );
  OAI21X1 _356_ (
    .A(_96_),
    .B(_108_),
    .C(_109_),
    .Y(_11_)
  );
  OAI21X1 _357_ (
    .A(_93_),
    .B(_103_),
    .C(_104_),
    .Y(_110_)
  );
  NAND2X1 _358_ (
    .A(Xin1[1]),
    .B(_110_),
    .Y(_111_)
  );
  OR2X2 _359_ (
    .A(_110_),
    .B(Xin1[1]),
    .Y(_112_)
  );
  NAND2X1 _360_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  NAND2X1 _361_ (
    .A(Xcalc[3]),
    .B(_96_),
    .Y(_114_)
  );
  OAI21X1 _362_ (
    .A(_96_),
    .B(_113_),
    .C(_114_),
    .Y(_12_)
  );
  NOR2X1 _363_ (
    .A(Xin1[0]),
    .B(Xin1[1]),
    .Y(_115_)
  );
  NAND2X1 _364_ (
    .A(_106_),
    .B(_115_),
    .Y(_116_)
  );
  NAND3X1 _365_ (
    .A(ISreg),
    .B(Xin12b[4]),
    .C(_116_),
    .Y(_117_)
  );
  INVX1 _366_ (
    .A(Xin12b[4]),
    .Y(_118_)
  );
  AND2X2 _367_ (
    .A(_106_),
    .B(_115_),
    .Y(_119_)
  );
  OAI21X1 _368_ (
    .A(_93_),
    .B(_119_),
    .C(_118_),
    .Y(_120_)
  );
  NAND2X1 _369_ (
    .A(_117_),
    .B(_120_),
    .Y(_121_)
  );
  NAND2X1 _370_ (
    .A(Xcalc[4]),
    .B(_96_),
    .Y(_122_)
  );
  OAI21X1 _371_ (
    .A(_96_),
    .B(_121_),
    .C(_122_),
    .Y(_13_)
  );
  INVX1 _372_ (
    .A(Xin12b[5]),
    .Y(_123_)
  );
  OAI21X1 _373_ (
    .A(Xin12b[4]),
    .B(_116_),
    .C(ISreg),
    .Y(_124_)
  );
  OR2X2 _374_ (
    .A(_124_),
    .B(_123_),
    .Y(_125_)
  );
  NAND2X1 _375_ (
    .A(_123_),
    .B(_124_),
    .Y(_126_)
  );
  NAND2X1 _376_ (
    .A(_126_),
    .B(_125_),
    .Y(_127_)
  );
  NAND2X1 _377_ (
    .A(Xcalc[5]),
    .B(_96_),
    .Y(_128_)
  );
  OAI21X1 _378_ (
    .A(_96_),
    .B(_127_),
    .C(_128_),
    .Y(_14_)
  );
  NOR2X1 _379_ (
    .A(Xin12b[4]),
    .B(Xin12b[5]),
    .Y(_129_)
  );
  NAND2X1 _380_ (
    .A(_129_),
    .B(_119_),
    .Y(_130_)
  );
  NAND3X1 _381_ (
    .A(ISreg),
    .B(Xin12b[6]),
    .C(_130_),
    .Y(_131_)
  );
  INVX1 _382_ (
    .A(Xin12b[6]),
    .Y(_132_)
  );
  NAND2X1 _383_ (
    .A(ISreg),
    .B(_130_),
    .Y(_133_)
  );
  NAND2X1 _384_ (
    .A(_132_),
    .B(_133_),
    .Y(_134_)
  );
  NAND2X1 _385_ (
    .A(_131_),
    .B(_134_),
    .Y(_135_)
  );
  NAND2X1 _386_ (
    .A(Xcalc[6]),
    .B(_96_),
    .Y(_136_)
  );
  OAI21X1 _387_ (
    .A(_96_),
    .B(_135_),
    .C(_136_),
    .Y(_15_)
  );
  INVX1 _388_ (
    .A(Xcalc[7]),
    .Y(_137_)
  );
  NAND3X1 _389_ (
    .A(_132_),
    .B(_129_),
    .C(_119_),
    .Y(_138_)
  );
  NAND3X1 _390_ (
    .A(ISreg),
    .B(Xin12b[7]),
    .C(_138_),
    .Y(_139_)
  );
  INVX1 _391_ (
    .A(Xin12b[7]),
    .Y(_140_)
  );
  NAND2X1 _392_ (
    .A(ISreg),
    .B(Xin12b[6]),
    .Y(_141_)
  );
  NAND3X1 _393_ (
    .A(_140_),
    .B(_141_),
    .C(_133_),
    .Y(_142_)
  );
  NAND3X1 _394_ (
    .A(LoadCtl[6]),
    .B(_139_),
    .C(_142_),
    .Y(_143_)
  );
  OAI21X1 _395_ (
    .A(_137_),
    .B(LoadCtl[6]),
    .C(_143_),
    .Y(_16_)
  );
  INVX1 _396_ (
    .A(Xin12b[8]),
    .Y(_144_)
  );
  NOR2X1 _397_ (
    .A(Xin12b[6]),
    .B(Xin12b[7]),
    .Y(_145_)
  );
  NAND2X1 _398_ (
    .A(_129_),
    .B(_145_),
    .Y(_146_)
  );
  OAI21X1 _399_ (
    .A(_116_),
    .B(_146_),
    .C(ISreg),
    .Y(_147_)
  );
  OR2X2 _400_ (
    .A(_147_),
    .B(_144_),
    .Y(_148_)
  );
  NAND2X1 _401_ (
    .A(_144_),
    .B(_147_),
    .Y(_149_)
  );
  NAND2X1 _402_ (
    .A(_149_),
    .B(_148_),
    .Y(_150_)
  );
  NAND2X1 _403_ (
    .A(Xcalc[8]),
    .B(_96_),
    .Y(_151_)
  );
  OAI21X1 _404_ (
    .A(_96_),
    .B(_150_),
    .C(_151_),
    .Y(_17_)
  );
  INVX1 _405_ (
    .A(Xcalc[9]),
    .Y(_152_)
  );
  INVX1 _406_ (
    .A(Xin12b[9]),
    .Y(_153_)
  );
  OAI21X1 _407_ (
    .A(_93_),
    .B(_144_),
    .C(_147_),
    .Y(_154_)
  );
  OR2X2 _408_ (
    .A(_154_),
    .B(_153_),
    .Y(_155_)
  );
  AOI21X1 _409_ (
    .A(_154_),
    .B(_153_),
    .C(_96_),
    .Y(_156_)
  );
  AOI22X1 _410_ (
    .A(_152_),
    .B(_96_),
    .C(_155_),
    .D(_156_),
    .Y(_18_)
  );
  INVX1 _411_ (
    .A(Xcalc[10]),
    .Y(_157_)
  );
  AND2X2 _412_ (
    .A(_129_),
    .B(_145_),
    .Y(_158_)
  );
  NOR2X1 _413_ (
    .A(Xin12b[8]),
    .B(Xin12b[9]),
    .Y(_159_)
  );
  NAND3X1 _414_ (
    .A(_159_),
    .B(_119_),
    .C(_158_),
    .Y(_160_)
  );
  NAND3X1 _415_ (
    .A(ISreg),
    .B(Xin12b[10]),
    .C(_160_),
    .Y(_161_)
  );
  INVX1 _416_ (
    .A(Xin12b[10]),
    .Y(_162_)
  );
  NAND2X1 _417_ (
    .A(ISreg),
    .B(_160_),
    .Y(_163_)
  );
  NAND2X1 _418_ (
    .A(_162_),
    .B(_163_),
    .Y(_164_)
  );
  NAND3X1 _419_ (
    .A(LoadCtl[6]),
    .B(_161_),
    .C(_164_),
    .Y(_165_)
  );
  OAI21X1 _420_ (
    .A(_157_),
    .B(LoadCtl[6]),
    .C(_165_),
    .Y(_19_)
  );
  NAND2X1 _421_ (
    .A(Xcalc[11]),
    .B(_96_),
    .Y(_166_)
  );
  INVX1 _422_ (
    .A(Xin12b[11]),
    .Y(_167_)
  );
  NAND2X1 _423_ (
    .A(selSign),
    .B(_167_),
    .Y(_168_)
  );
  INVX1 _424_ (
    .A(selSign),
    .Y(_169_)
  );
  NAND2X1 _425_ (
    .A(Xin12b[11]),
    .B(_169_),
    .Y(_170_)
  );
  NAND2X1 _426_ (
    .A(_168_),
    .B(_170_),
    .Y(_171_)
  );
  INVX1 _427_ (
    .A(_171_),
    .Y(_172_)
  );
  NAND2X1 _428_ (
    .A(ISreg),
    .B(Xin12b[10]),
    .Y(_173_)
  );
  NAND3X1 _429_ (
    .A(_172_),
    .B(_173_),
    .C(_163_),
    .Y(_174_)
  );
  OAI21X1 _430_ (
    .A(Xin12b[8]),
    .B(Xin12b[9]),
    .C(ISreg),
    .Y(_175_)
  );
  NAND3X1 _431_ (
    .A(_175_),
    .B(_173_),
    .C(_147_),
    .Y(_176_)
  );
  NAND2X1 _432_ (
    .A(_171_),
    .B(_176_),
    .Y(_177_)
  );
  NAND3X1 _433_ (
    .A(LoadCtl[6]),
    .B(_177_),
    .C(_174_),
    .Y(_178_)
  );
  NAND2X1 _434_ (
    .A(_166_),
    .B(_178_),
    .Y(_20_)
  );
  NAND2X1 _435_ (
    .A(Yin0[0]),
    .B(LoadCtl[6]),
    .Y(_179_)
  );
  OAI21X1 _436_ (
    .A(LoadCtl[6]),
    .B(_49_),
    .C(_179_),
    .Y(_21_)
  );
  NAND3X1 _437_ (
    .A(Yin0[0]),
    .B(Yin0[1]),
    .C(ISreg),
    .Y(_180_)
  );
  OAI21X1 _438_ (
    .A(_89_),
    .B(_93_),
    .C(_91_),
    .Y(_181_)
  );
  NAND3X1 _439_ (
    .A(LoadCtl[6]),
    .B(_180_),
    .C(_181_),
    .Y(_182_)
  );
  OAI21X1 _440_ (
    .A(_51_),
    .B(LoadCtl[6]),
    .C(_182_),
    .Y(_22_)
  );
  INVX1 _441_ (
    .A(Yin1[0]),
    .Y(_183_)
  );
  OAI21X1 _442_ (
    .A(Yin0[0]),
    .B(Yin0[1]),
    .C(ISreg),
    .Y(_184_)
  );
  OR2X2 _443_ (
    .A(_184_),
    .B(_183_),
    .Y(_185_)
  );
  NOR2X1 _444_ (
    .A(Yin0[0]),
    .B(Yin0[1]),
    .Y(_186_)
  );
  OAI21X1 _445_ (
    .A(_93_),
    .B(_186_),
    .C(_183_),
    .Y(_187_)
  );
  NAND3X1 _446_ (
    .A(LoadCtl[6]),
    .B(_187_),
    .C(_185_),
    .Y(_188_)
  );
  OAI21X1 _447_ (
    .A(_53_),
    .B(LoadCtl[6]),
    .C(_188_),
    .Y(_23_)
  );
  OAI21X1 _448_ (
    .A(_93_),
    .B(_183_),
    .C(_184_),
    .Y(_189_)
  );
  NAND2X1 _449_ (
    .A(Yin1[1]),
    .B(_189_),
    .Y(_190_)
  );
  OR2X2 _450_ (
    .A(_189_),
    .B(Yin1[1]),
    .Y(_191_)
  );
  NAND3X1 _451_ (
    .A(LoadCtl[6]),
    .B(_190_),
    .C(_191_),
    .Y(_192_)
  );
  OAI21X1 _452_ (
    .A(_55_),
    .B(LoadCtl[6]),
    .C(_192_),
    .Y(_24_)
  );
  NOR2X1 _453_ (
    .A(Yin1[0]),
    .B(Yin1[1]),
    .Y(_193_)
  );
  NAND2X1 _454_ (
    .A(_186_),
    .B(_193_),
    .Y(_194_)
  );
  NAND2X1 _455_ (
    .A(ISreg),
    .B(_194_),
    .Y(_195_)
  );
  OR2X2 _456_ (
    .A(_195_),
    .B(_78_),
    .Y(_196_)
  );
  AND2X2 _457_ (
    .A(_186_),
    .B(_193_),
    .Y(_197_)
  );
  OAI21X1 _458_ (
    .A(_93_),
    .B(_197_),
    .C(_78_),
    .Y(_198_)
  );
  NAND3X1 _459_ (
    .A(LoadCtl[6]),
    .B(_198_),
    .C(_196_),
    .Y(_199_)
  );
  OAI21X1 _460_ (
    .A(_57_),
    .B(LoadCtl[6]),
    .C(_199_),
    .Y(_25_)
  );
  OAI21X1 _461_ (
    .A(_93_),
    .B(_78_),
    .C(_195_),
    .Y(_200_)
  );
  OR2X2 _462_ (
    .A(_200_),
    .B(_82_),
    .Y(_201_)
  );
  AOI21X1 _463_ (
    .A(_200_),
    .B(_82_),
    .C(_96_),
    .Y(_202_)
  );
  AOI22X1 _464_ (
    .A(_59_),
    .B(_96_),
    .C(_201_),
    .D(_202_),
    .Y(_26_)
  );
  NOR2X1 _465_ (
    .A(Yin12b[4]),
    .B(Yin12b[5]),
    .Y(_203_)
  );
  NAND2X1 _466_ (
    .A(_203_),
    .B(_197_),
    .Y(_204_)
  );
  NAND3X1 _467_ (
    .A(ISreg),
    .B(Yin12b[6]),
    .C(_204_),
    .Y(_205_)
  );
  INVX1 _468_ (
    .A(Yin12b[6]),
    .Y(_206_)
  );
  NAND2X1 _469_ (
    .A(ISreg),
    .B(_204_),
    .Y(_207_)
  );
  NAND2X1 _470_ (
    .A(_206_),
    .B(_207_),
    .Y(_208_)
  );
  NAND3X1 _471_ (
    .A(LoadCtl[6]),
    .B(_205_),
    .C(_208_),
    .Y(_209_)
  );
  OAI21X1 _472_ (
    .A(_61_),
    .B(LoadCtl[6]),
    .C(_209_),
    .Y(_27_)
  );
  NAND3X1 _473_ (
    .A(_206_),
    .B(_203_),
    .C(_197_),
    .Y(_210_)
  );
  NAND3X1 _474_ (
    .A(ISreg),
    .B(Yin12b[7]),
    .C(_210_),
    .Y(_211_)
  );
  INVX1 _475_ (
    .A(Yin12b[7]),
    .Y(_212_)
  );
  NAND2X1 _476_ (
    .A(ISreg),
    .B(Yin12b[6]),
    .Y(_213_)
  );
  NAND3X1 _477_ (
    .A(_212_),
    .B(_213_),
    .C(_207_),
    .Y(_214_)
  );
  NAND3X1 _478_ (
    .A(LoadCtl[6]),
    .B(_211_),
    .C(_214_),
    .Y(_215_)
  );
  OAI21X1 _479_ (
    .A(_63_),
    .B(LoadCtl[6]),
    .C(_215_),
    .Y(_28_)
  );
  INVX1 _480_ (
    .A(Yin12b[8]),
    .Y(_216_)
  );
  NOR2X1 _481_ (
    .A(Yin12b[6]),
    .B(Yin12b[7]),
    .Y(_217_)
  );
  NAND2X1 _482_ (
    .A(_203_),
    .B(_217_),
    .Y(_218_)
  );
  OAI21X1 _483_ (
    .A(_194_),
    .B(_218_),
    .C(ISreg),
    .Y(_219_)
  );
  OR2X2 _484_ (
    .A(_219_),
    .B(_216_),
    .Y(_220_)
  );
  NAND2X1 _485_ (
    .A(_216_),
    .B(_219_),
    .Y(_221_)
  );
  NAND2X1 _486_ (
    .A(_221_),
    .B(_220_),
    .Y(_222_)
  );
  NAND2X1 _487_ (
    .A(Ycalc[8]),
    .B(_96_),
    .Y(_223_)
  );
  OAI21X1 _488_ (
    .A(_96_),
    .B(_222_),
    .C(_223_),
    .Y(_29_)
  );
  INVX1 _489_ (
    .A(Yin12b[9]),
    .Y(_224_)
  );
  OAI21X1 _490_ (
    .A(_93_),
    .B(_216_),
    .C(_219_),
    .Y(_225_)
  );
  OR2X2 _491_ (
    .A(_225_),
    .B(_224_),
    .Y(_226_)
  );
  AOI21X1 _492_ (
    .A(_225_),
    .B(_224_),
    .C(_96_),
    .Y(_227_)
  );
  AOI22X1 _493_ (
    .A(_67_),
    .B(_96_),
    .C(_226_),
    .D(_227_),
    .Y(_30_)
  );
  AND2X2 _494_ (
    .A(_203_),
    .B(_217_),
    .Y(_228_)
  );
  NOR2X1 _495_ (
    .A(Yin12b[8]),
    .B(Yin12b[9]),
    .Y(_229_)
  );
  NAND3X1 _496_ (
    .A(_229_),
    .B(_197_),
    .C(_228_),
    .Y(_230_)
  );
  NAND3X1 _497_ (
    .A(ISreg),
    .B(Yin12b[10]),
    .C(_230_),
    .Y(_231_)
  );
  INVX1 _498_ (
    .A(Yin12b[10]),
    .Y(_232_)
  );
  NAND2X1 _499_ (
    .A(ISreg),
    .B(_230_),
    .Y(_233_)
  );
  NAND2X1 _500_ (
    .A(_232_),
    .B(_233_),
    .Y(_234_)
  );
  NAND3X1 _501_ (
    .A(LoadCtl[6]),
    .B(_231_),
    .C(_234_),
    .Y(_235_)
  );
  OAI21X1 _502_ (
    .A(_69_),
    .B(LoadCtl[6]),
    .C(_235_),
    .Y(_31_)
  );
  NAND2X1 _503_ (
    .A(Ycalc[11]),
    .B(_96_),
    .Y(_236_)
  );
  INVX1 _504_ (
    .A(Yin12b[11]),
    .Y(_237_)
  );
  NAND2X1 _505_ (
    .A(selSign),
    .B(_237_),
    .Y(_238_)
  );
  NAND2X1 _506_ (
    .A(Yin12b[11]),
    .B(_169_),
    .Y(_239_)
  );
  NAND2X1 _507_ (
    .A(_238_),
    .B(_239_),
    .Y(_240_)
  );
  INVX1 _508_ (
    .A(_240_),
    .Y(_241_)
  );
  NAND2X1 _509_ (
    .A(ISreg),
    .B(Yin12b[10]),
    .Y(_242_)
  );
  NAND3X1 _510_ (
    .A(_241_),
    .B(_242_),
    .C(_233_),
    .Y(_243_)
  );
  OAI21X1 _511_ (
    .A(Yin12b[8]),
    .B(Yin12b[9]),
    .C(ISreg),
    .Y(_244_)
  );
  NAND3X1 _512_ (
    .A(_244_),
    .B(_242_),
    .C(_219_),
    .Y(_245_)
  );
  NAND2X1 _513_ (
    .A(_240_),
    .B(_245_),
    .Y(_246_)
  );
  NAND3X1 _514_ (
    .A(LoadCtl[6]),
    .B(_246_),
    .C(_243_),
    .Y(_247_)
  );
  NAND2X1 _515_ (
    .A(_236_),
    .B(_247_),
    .Y(_32_)
  );
  NOR2X1 _516_ (
    .A(LoadCtl[2]),
    .B(LoadCtl[3]),
    .Y(_248_)
  );
  AND2X2 _517_ (
    .A(_75_),
    .B(_248_),
    .Y(_249_)
  );
  NAND2X1 _518_ (
    .A(LoadCtl[5]),
    .B(_249_),
    .Y(_250_)
  );
  NOR2X1 _519_ (
    .A(LoadCtl[4]),
    .B(_250_),
    .Y(_251_)
  );
  NAND2X1 _520_ (
    .A(Xin[0]),
    .B(_251_),
    .Y(_252_)
  );
  OAI21X1 _521_ (
    .A(_162_),
    .B(_251_),
    .C(_252_),
    .Y(_33_)
  );
  NAND2X1 _522_ (
    .A(Xin[1]),
    .B(_251_),
    .Y(_253_)
  );
  OAI21X1 _523_ (
    .A(_167_),
    .B(_251_),
    .C(_253_),
    .Y(_34_)
  );
  INVX1 _524_ (
    .A(Xin[0]),
    .Y(_254_)
  );
  NAND2X1 _525_ (
    .A(LoadCtl[4]),
    .B(_249_),
    .Y(_255_)
  );
  NAND2X1 _526_ (
    .A(Xin12b[8]),
    .B(_255_),
    .Y(_256_)
  );
  OAI21X1 _527_ (
    .A(_254_),
    .B(_255_),
    .C(_256_),
    .Y(_35_)
  );
  INVX1 _528_ (
    .A(Xin[1]),
    .Y(_257_)
  );
  NAND2X1 _529_ (
    .A(Xin12b[9]),
    .B(_255_),
    .Y(_258_)
  );
  OAI21X1 _530_ (
    .A(_257_),
    .B(_255_),
    .C(_258_),
    .Y(_36_)
  );
  NAND2X1 _531_ (
    .A(Xin12b[6]),
    .B(_76_),
    .Y(_259_)
  );
  OAI21X1 _532_ (
    .A(_254_),
    .B(_76_),
    .C(_259_),
    .Y(_37_)
  );
  NAND2X1 _533_ (
    .A(Xin12b[7]),
    .B(_76_),
    .Y(_260_)
  );
  OAI21X1 _534_ (
    .A(_257_),
    .B(_76_),
    .C(_260_),
    .Y(_38_)
  );
  NAND2X1 _535_ (
    .A(Xin[0]),
    .B(_80_),
    .Y(_261_)
  );
  OAI21X1 _536_ (
    .A(_118_),
    .B(_80_),
    .C(_261_),
    .Y(_39_)
  );
  NAND2X1 _537_ (
    .A(Xin[1]),
    .B(_80_),
    .Y(_262_)
  );
  OAI21X1 _538_ (
    .A(_123_),
    .B(_80_),
    .C(_262_),
    .Y(_40_)
  );
  OAI21X1 _539_ (
    .A(LoadCtl[0]),
    .B(_85_),
    .C(Xin1[0]),
    .Y(_263_)
  );
  OAI21X1 _540_ (
    .A(_254_),
    .B(_86_),
    .C(_263_),
    .Y(_41_)
  );
  OAI21X1 _541_ (
    .A(LoadCtl[0]),
    .B(_85_),
    .C(Xin1[1]),
    .Y(_264_)
  );
  OAI21X1 _542_ (
    .A(_257_),
    .B(_86_),
    .C(_264_),
    .Y(_42_)
  );
  NAND2X1 _543_ (
    .A(LoadCtl[0]),
    .B(Xin[0]),
    .Y(_265_)
  );
  OAI21X1 _544_ (
    .A(LoadCtl[0]),
    .B(_95_),
    .C(_265_),
    .Y(_43_)
  );
  NAND2X1 _545_ (
    .A(LoadCtl[0]),
    .B(Xin[1]),
    .Y(_266_)
  );
  OAI21X1 _546_ (
    .A(LoadCtl[0]),
    .B(_99_),
    .C(_266_),
    .Y(_44_)
  );
  NAND2X1 _547_ (
    .A(Yin[0]),
    .B(_251_),
    .Y(_267_)
  );
  OAI21X1 _548_ (
    .A(_232_),
    .B(_251_),
    .C(_267_),
    .Y(_45_)
  );
  NAND2X1 _549_ (
    .A(Yin[1]),
    .B(_251_),
    .Y(_268_)
  );
  OAI21X1 _550_ (
    .A(_237_),
    .B(_251_),
    .C(_268_),
    .Y(_46_)
  );
  NAND2X1 _551_ (
    .A(Yin12b[8]),
    .B(_255_),
    .Y(_269_)
  );
  OAI21X1 _552_ (
    .A(_84_),
    .B(_255_),
    .C(_269_),
    .Y(_47_)
  );
  NAND2X1 _553_ (
    .A(Yin12b[9]),
    .B(_255_),
    .Y(_270_)
  );
  OAI21X1 _554_ (
    .A(_73_),
    .B(_255_),
    .C(_270_),
    .Y(_48_)
  );
  NAND2X1 _555_ (
    .A(Yin12b[6]),
    .B(_76_),
    .Y(_271_)
  );
  OAI21X1 _556_ (
    .A(_84_),
    .B(_76_),
    .C(_271_),
    .Y(_0_)
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:26.2-26.53" *)
  DFFPOSX1 _557_ (
    .CLK(clk),
    .D(_8_),
    .Q(ISreg)
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _558_ (
    .CLK(clk),
    .D(_9_),
    .Q(Xcalc[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _559_ (
    .CLK(clk),
    .D(_10_),
    .Q(Xcalc[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _560_ (
    .CLK(clk),
    .D(_11_),
    .Q(Xcalc[2])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _561_ (
    .CLK(clk),
    .D(_12_),
    .Q(Xcalc[3])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _562_ (
    .CLK(clk),
    .D(_13_),
    .Q(Xcalc[4])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _563_ (
    .CLK(clk),
    .D(_14_),
    .Q(Xcalc[5])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _564_ (
    .CLK(clk),
    .D(_15_),
    .Q(Xcalc[6])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _565_ (
    .CLK(clk),
    .D(_16_),
    .Q(Xcalc[7])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _566_ (
    .CLK(clk),
    .D(_17_),
    .Q(Xcalc[8])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _567_ (
    .CLK(clk),
    .D(_18_),
    .Q(Xcalc[9])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _568_ (
    .CLK(clk),
    .D(_19_),
    .Q(Xcalc[10])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _569_ (
    .CLK(clk),
    .D(_20_),
    .Q(Xcalc[11])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _570_ (
    .CLK(clk),
    .D(_21_),
    .Q(Ycalc[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _571_ (
    .CLK(clk),
    .D(_22_),
    .Q(Ycalc[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _572_ (
    .CLK(clk),
    .D(_23_),
    .Q(Ycalc[2])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _573_ (
    .CLK(clk),
    .D(_24_),
    .Q(Ycalc[3])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _574_ (
    .CLK(clk),
    .D(_25_),
    .Q(Ycalc[4])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _575_ (
    .CLK(clk),
    .D(_26_),
    .Q(Ycalc[5])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _576_ (
    .CLK(clk),
    .D(_27_),
    .Q(Ycalc[6])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _577_ (
    .CLK(clk),
    .D(_28_),
    .Q(Ycalc[7])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _578_ (
    .CLK(clk),
    .D(_29_),
    .Q(Ycalc[8])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _579_ (
    .CLK(clk),
    .D(_30_),
    .Q(Ycalc[9])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _580_ (
    .CLK(clk),
    .D(_31_),
    .Q(Ycalc[10])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:52.2-63.5" *)
  DFFPOSX1 _581_ (
    .CLK(clk),
    .D(_32_),
    .Q(Ycalc[11])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _582_ (
    .CLK(clk),
    .D(_33_),
    .Q(Xin12b[10])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _583_ (
    .CLK(clk),
    .D(_34_),
    .Q(Xin12b[11])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _584_ (
    .CLK(clk),
    .D(_35_),
    .Q(Xin12b[8])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _585_ (
    .CLK(clk),
    .D(_36_),
    .Q(Xin12b[9])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _586_ (
    .CLK(clk),
    .D(_37_),
    .Q(Xin12b[6])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _587_ (
    .CLK(clk),
    .D(_38_),
    .Q(Xin12b[7])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _588_ (
    .CLK(clk),
    .D(_39_),
    .Q(Xin12b[4])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _589_ (
    .CLK(clk),
    .D(_40_),
    .Q(Xin12b[5])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _590_ (
    .CLK(clk),
    .D(_41_),
    .Q(Xin1[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _591_ (
    .CLK(clk),
    .D(_42_),
    .Q(Xin1[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _592_ (
    .CLK(clk),
    .D(_43_),
    .Q(Xin0[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _593_ (
    .CLK(clk),
    .D(_44_),
    .Q(Xin0[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _594_ (
    .CLK(clk),
    .D(_45_),
    .Q(Yin12b[10])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _595_ (
    .CLK(clk),
    .D(_46_),
    .Q(Yin12b[11])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _596_ (
    .CLK(clk),
    .D(_47_),
    .Q(Yin12b[8])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _597_ (
    .CLK(clk),
    .D(_48_),
    .Q(Yin12b[9])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _598_ (
    .CLK(clk),
    .D(_0_),
    .Q(Yin12b[6])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _599_ (
    .CLK(clk),
    .D(_1_),
    .Q(Yin12b[7])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _600_ (
    .CLK(clk),
    .D(_2_),
    .Q(Yin12b[4])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _601_ (
    .CLK(clk),
    .D(_3_),
    .Q(Yin12b[5])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _602_ (
    .CLK(clk),
    .D(_4_),
    .Q(Yin1[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _603_ (
    .CLK(clk),
    .D(_5_),
    .Q(Yin1[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _604_ (
    .CLK(clk),
    .D(_6_),
    .Q(Yin0[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:32.2-39.8" *)
  DFFPOSX1 _605_ (
    .CLK(clk),
    .D(_7_),
    .Q(Yin0[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _606_ (
    .CLK(clk),
    .D(Rdy),
    .Q(LoadCtl[0])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _607_ (
    .CLK(clk),
    .D(LoadCtl[0]),
    .Q(LoadCtl[1])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _608_ (
    .CLK(clk),
    .D(LoadCtl[1]),
    .Q(LoadCtl[2])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _609_ (
    .CLK(clk),
    .D(LoadCtl[2]),
    .Q(LoadCtl[3])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _610_ (
    .CLK(clk),
    .D(LoadCtl[3]),
    .Q(LoadCtl[4])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _611_ (
    .CLK(clk),
    .D(LoadCtl[4]),
    .Q(LoadCtl[5])
  );
  (* src = "/home/ji/ETRI-0.5um-CMOS-MPW-Std-Cell-DK/design/MyChip/2025_1st/NCO/2_Splited_IO/2_3_Output_Terminal/source/output_terminal.v:17.5-22.8" *)
  DFFPOSX1 _612_ (
    .CLK(clk),
    .D(LoadCtl[5]),
    .Q(LoadCtl[6])
  );
  (* keep = 32'd1 *)
  BUFX2 _613_ (
    .A(_272_[0]),
    .Y(Dout[0])
  );
  (* keep = 32'd1 *)
  BUFX2 _614_ (
    .A(_272_[1]),
    .Y(Dout[1])
  );
  (* keep = 32'd1 *)
  BUFX2 _615_ (
    .A(_272_[10]),
    .Y(Dout[10])
  );
  (* keep = 32'd1 *)
  BUFX2 _616_ (
    .A(_272_[11]),
    .Y(Dout[11])
  );
  (* keep = 32'd1 *)
  BUFX2 _617_ (
    .A(_272_[2]),
    .Y(Dout[2])
  );
  (* keep = 32'd1 *)
  BUFX2 _618_ (
    .A(_272_[3]),
    .Y(Dout[3])
  );
  (* keep = 32'd1 *)
  BUFX2 _619_ (
    .A(_272_[4]),
    .Y(Dout[4])
  );
  (* keep = 32'd1 *)
  BUFX2 _620_ (
    .A(_272_[5]),
    .Y(Dout[5])
  );
  (* keep = 32'd1 *)
  BUFX2 _621_ (
    .A(_272_[6]),
    .Y(Dout[6])
  );
  (* keep = 32'd1 *)
  BUFX2 _622_ (
    .A(_272_[7]),
    .Y(Dout[7])
  );
  (* keep = 32'd1 *)
  BUFX2 _623_ (
    .A(_272_[8]),
    .Y(Dout[8])
  );
  (* keep = 32'd1 *)
  BUFX2 _624_ (
    .A(_272_[9]),
    .Y(Dout[9])
  );
  (* keep = 32'd1 *)
  BUFX2 _625_ (
    .A(LoadCtl[6]),
    .Y(Vld)
  );
  assign Xin12b[3:0] = { Xin1, Xin0 };
  assign Yin12b[3:0] = { Yin1, Yin0 };
endmodule
